aspnet/LibraryManager

- src/LibraryManager.Vsix/Json/TextviewCreationListener.cs
- src/LibraryManager.Vsix/Shared/LibraryHelpers.cs
We no longer read the manifest from disk on save but from the the document TextBuffer.
> Fixing file lock bug on save. 

- src/LibraryManager.Vsix/Shared/LibraryHelpers.cs
VS crashes on restore when manifest does not have a provider specified
> Bug 577597 fix

- src/LibraryManager.Contracts/IProvider.cs
- src/LibraryManager.Vsix/Contracts/HostInteraction.cs
- src/LibraryManager.Vsix/ErrorList/ErrorList.cs
- src/LibraryManager.Vsix/Resources/Text.Designer.cs
- src/LibraryManager.Vsix/Resources/Text.resx
- src/LibraryManager.Vsix/Shared/LibraryHelpers.cs
- src/LibraryManager.Vsix/Shared/Telemetry.cs
- src/LibraryManager/Manifest.cs
- src/LibraryManager/Providers/Cdnjs/CdnjsProvider.cs
- src/LibraryManager/Providers/FileSystem/FileSystemProvider.cs
- src/LibraryManager/Resources/Text.Designer.cs
- src/LibraryManager/Resources/Text.resx
- test/LibraryManager.Mocks/Provider.cs
It's a bit ugly but I think it's OK for preview 3. Not sure if we should propagate the update failure out and fail the entire Clean operation (may have cleaned some but not all libraries - success or failure?).
We should test the FileSystem provider though as well. The code says Files should be required, not sure if it's enforced.
> Fixing bug 568284 (nullref on Clean command).

- src/LibraryManager.Vsix/Contracts/HostInteraction.cs
- src/LibraryManager.Vsix/Json/FileIdentifier.cs
- src/LibraryManager.Vsix/Json/TextviewCreationListener.cs
- src/LibraryManager.Vsix/Microsoft.Web.LibraryManager.Vsix.csproj
Code wans't using library version number when doing comparison of files from the old and new libraries, only relative installation path (which has no version info in it). Adding version info temporarily for comparison (then removing prior to installation). A bit dirty. Please comment if you think we want a cleaner fix (use a class / tuple with file path and version number as fields rather than just a path?)
> Fix for bug 568371 (changes in library version are ignored)

- src/LibraryManager.Vsix/Json/TextviewCreationListener.cs
- src/LibraryManager.Vsix/Microsoft.Web.LibraryManager.Vsix.csproj
- src/LibraryManager/Providers/Cdnjs/CdnjsProvider.cs
- test/LibraryManager.Test/ManifestTest.cs
- When a libman.json file fails to parse initially, we get a null manifest leading to exceptions
> Fixing restore bug: 578106

- src/LibraryManager.Vsix/Microsoft.Web.LibraryManager.Vsix.csproj
Fixing FileNotFoundException when trying to load Nuget.VisualStudio. 
This failure started happening after we moved to packageReferences. Updating the version of the package fixes the issue.
> Fixing FileNotFoundException when trying to load Nuget.VisualStudio.

- src/LibraryManager.Vsix/Json/JsonHelpers.cs
Bug 588017: LibMan: library property completion does not work if there is no defaultPath specified
This is a regression introduced during the schema change PR.
> Fixing unecessary check for validation of InstallationState

- src/LibraryManager.Build/Microsoft.Web.LibraryManager.Build.csproj
- src/LibraryManager.Contracts/Microsoft.Web.LibraryManager.Contracts.csproj
- src/LibraryManager/Microsoft.Web.LibraryManager.csproj
Set PrivateAssets on references to prevent them from leaking into the consuming project for the Build nupkg.
> Private assets

- src/LibraryManager.Vsix/source.extension.vsixmanifest
Even though VS has started using the Minor version value, VSIXes still need to use 15.0.<build> to target a specific release.
> Fixes InstallationTarget for 15.6

- src/LibraryManager.Vsix/Json/Completion/CompletionController.cs
- src/LibraryManager.Vsix/Json/Completion/LibraryIdCompletionProvider.cs
- src/LibraryManager.Vsix/Json/TextviewCreationListener.cs
Fixing bug 568369 - [LibMan] IntelliSense too slow in library.json
Library name completion is slow because we are getting library names from a network request. We should look into caching them both to speed up completion and to enable offline scenarios (at least somewhat). For now the fix is scoped to avoiding the wrong completion of library name. It was possible to get completely wrong library name completion because we were leaving completion list up while the user was typing new characters of library name. The list wasn't getting either dismissed or filtered. In general, CompletionController needs design review and will possibly be re-written. For now I'm adding a workaround to make it work similar to NPM package.json library name completion, where we immediately dimiss completion list …
> Fixing incorrect library name IntelliSense

- src/LibraryManager.Vsix/LibraryManagerPackage.cs
We now have the PackageLoader that determines the need to load LibMan to avoid loading this package unnecessarily.
> Remove auto load from LibMan package

- src/LibraryManager.Contracts/Microsoft.Web.LibraryManager.Contracts.csproj
- src/LibraryManager/Microsoft.Web.LibraryManager.csproj
Fixing
The type initializer for 'Microsoft.Web.LibraryManager.WebRequestHandler' threw an exception. - FileNotFoundException: Could not load file or assembly 'System.Net.Http, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
First of all, Microsoft.Web.LibraryManager.Contracts.csproj has 
<PackageReference Include="System.Net.Http" Version="$(SystemNetHttpPackageVersion)" Condition="'$(TargetFramework)' != 'netstandard2.0'" />
which it doesn't seem to need. Only Microsoft.Web.LibraryManager.csproj seems to need System.Net.Http.
Second, Microsoft.Web.LibraryManager.csproj  current uses
<PackageReference Include="System.Net.Http" Version="$(SystemNetHttpPackageVersion)" />
netstandard20 already includes …
> Fixing System.Net.Http reference

- src/LibraryManager.Vsix/UI/InstallDialog.xaml
- src/LibraryManager.Vsix/UI/InstallDialog.xaml.cs
Close dialog when install button is clicked to prevent UI hangs for unPkg provider.
> Close dialog when install button is clicked

- src/libman/Commands/BaseCommand.cs
- src/libman/Commands/InitCommand.cs
- src/libman/Commands/InstallCommand.cs
- src/libman/Contracts/ConsoleLogger.cs
- test/libman.Test/LibmanInitTests.cs
- test/libman.Test/LibmanInstallTest.cs
- test/libman.Test/SampleTestCommand.cs
Changes:
- During init prompt for `DefaultProvider` with a suggested default of `cdnjs` (System default)
- For the prompts, keep the console on the same line instead of forcing the user to the next line.
- During `install` if libman.json doesn't exist, changed the behavior to write the json file to disk and then to read it again, so we get hold of proper defaults to use for validation.
> Fix prompts for Init and Install CLI commands

- src/LibraryManager.Vsix/Microsoft.Web.LibraryManager.Vsix.csproj
Since this VSIX ships in VS, we should always set this to true.  This
allows a private build of the VSIX to install over the one included in
VS.
The tradeoff is that a privately built VSIX will not be able to install
on a VS instance which did not install LibraryManager already.
> Always set IsProductComponent to true

- src/libman/Commands/UpdateCommand.cs
- src/libman/Resources.Designer.cs
- src/libman/Resources.resx
- test/libman.Test/LibmanUpdateTest.cs
**Unchanged syntax:**
1. `libman update jquery`   -- this will update `jquery` (any installed version) to the latest version
**No longer allowed syntax:** 
1. `libman update jquery@2.2.0`  -- earlier this would update `jquery@2.2.0` to the latest version
1. `libman update jquery@2.2.0 --to jquery@2.2.1`  -- earlier this would update `jquery@2.2.0` to `jquery@2.2.1`
**New syntax:**
1. `libman update jquery --to 2.2.1`  -- this will udpate jquery (any installed version) to the specified version.
Changed argument `libraryId` to `libraryName` along with its help text.
/cc @justcla
> Change syntax for CLI update command

- src/LibraryManager.Vsix/Json/Completion/FilesCompletionProvider.cs
- src/LibraryManager.Vsix/Json/Completion/LibraryIdCompletionProvider.cs
- src/LibraryManager.Vsix/Json/Completion/SimpleCompletionEntry.cs
- test/LibraryManager.IntegrationTest/LibmanCompletionTests.cs
Do not make "Loading..." getting inserted when committed (enter or tab) during the time Loading for completion list.
> Do not make "Loading..." getting inserted when commited

- src/LibraryManager.Build/Contracts/HostInteraction.cs
- src/LibraryManager.Contracts/FileHelpers.cs
- src/LibraryManager.Vsix/Contracts/HostInteraction.cs
- src/LibraryManager/CacheService/CacheService.cs
- src/libman/Contracts/HostInteraction.cs
Fix for internal bug 612818 [LibMan] Download huge file and quit VS: partial download orphaned.
The fix is to 
1. Save file stream to a temporary file first
2. Once all stream content is saved locally, move the temp file to the destination file
3. Clean up temporary file/folder
This should greatly reduce the likelihood of ending up with a  corrupt/partially downloaded file if the user exits VS before file  download is complete.
> Fix incomplete file download

- src/libman/Commands/UninstallCommand.cs
- src/libman/LibraryResolver.cs
- test/libman.Test/LibraryResolverTest.cs
- `LibraryResolver` No longer uses Catalogs to resolve names to Ids.
Earlier `LibraryResolver` would try to ask each catalog to check if the given term matched display name or library. 
Now since we have information about name and version of each library in the manifest, we no longer need to ask the Catalog.
> Change LibraryResolver to resolve using LibraryId or LibraryName

- src/LibraryManager.Vsix/UI/InstallDialog.xaml
Fix for issue:
https://github.com/aspnet/LibraryManager/issues/204
Tabbing after editing target location should put focus on "Install" button if its enabled.
> Fixing tab navigation issue

- LibraryManager.msbuild
The signing builds look for nupkgs in the `artifacts\$(configuration)` folder.
> Change output path of CLI nuget package

- src/LibraryManager.Vsix/UI/InstallDialog.xaml
- src/LibraryManager.Vsix/UI/InstallDialog.xaml.cs
This is not required as I made changes to use default tab navigation order here:
https://github.com/aspnet/LibraryManager/commit/a4e7ce8b60fab50dba2c370fb799b2166c44bbc9
This actually breaks provider selection using mouse.
> Remove PreviewMouseDown handler

- src/LibraryManager.Vsix/UI/Controls/EditorTooltip.xaml
- src/LibraryManager.Vsix/UI/Controls/Library.xaml
- src/LibraryManager.Vsix/UI/Controls/TargetLocation.xaml
- src/LibraryManager.Vsix/UI/InstallDialog.xaml
Fixing https://github.com/aspnet/LibraryManager/issues/163 - **Autocomplete of 'jquerycarousel' becomes 'jquery_carousel'**
The issue here was that ```<AccessText>``` was used in our UI instead of ```<TextBlock>``` for some reason. AccessText uses ```_``` character as a special meta-character to specify that the following character is the "access key", so the ```_``` is not normally visible (until you press Alt button). Pressing the access key will invoke OnAccessKey method of the control using AccessText. It doesn't look that functionality was being used at all. I looked through all of our xaml and replaced all uses of AccessText with TextBlock. None of the uses of AccessText were taking advantage of the access key functionality or handling OnAccessKey method.
For more info, see …
> Fix missing underscores in library names in the UI

- src/LibraryManager/Manifest.cs
- test/LibraryManager.Test/ManifestTest.cs
- test/libman.Test/LibmanInstallTest.cs
When adding a package:
- if the defaultProvider is not set, set it to the current provider
- If the defaultProvider is set and does not match the current provider, set the 'provider' on the library
- If the defaultProvider is set and matches the current provider, do nothing
Follow the same behavior from
- UI Add Library dialog
- CLI install command
> Set default provider when installing libraries

- src/LibraryManager.Vsix/Json/SuggestedActions/UpdateSuggestedActionSet.cs
- src/LibraryManager/Providers/Cdnjs/CdnjsCatalog.cs
- src/LibraryManager/Providers/FileSystem/FileSystemCatalog.cs
- src/LibraryManager/Providers/Unpkg/UnpkgLibraryGroup.cs
- src/libman/Commands/InstallCommand.cs
- src/libman/Commands/UpdateCommand.cs
- test/LibraryManager.Test/Providers/Cdnjs/CdnjsCatalogTest.cs
- test/LibraryManager.Test/Providers/FileSystem/FileSystemCatalogTest.cs
Fixes #157 
- Makes unpkg and cdnjs providers consistent:
- `GetLatestVersion()` now returns only the version part for both cdnjs and unpkg
- `Catalog.GetLibraryIds()` now returns the full libraryIds for unpkg
- FileSystem provider returns empty string for `GetLatestVersion()`
- `UpdateSuggestedActionSet` combines the library's `displayname` and `latestVersion` to show the update suggestion.
> Fix CLI install via unpkg

- LibraryManager.sln
- src/LibraryManager.Contracts/IProvider.cs
- src/LibraryManager/LibraryInstallationState.cs
- src/LibraryManager/LibraryNaming/ILibraryNamingScheme.cs
- src/LibraryManager/LibraryNaming/LibraryIdToNameAndVersionConverter.cs
- src/LibraryManager/LibraryNaming/SimpleLibraryNamingScheme.cs
- src/LibraryManager/LibraryNaming/VersionedLibraryNamingScheme.cs
- src/LibraryManager/Manifest.cs
- src/LibraryManager/Providers/Cdnjs/CdnjsCatalog.cs
- src/LibraryManager/Providers/Cdnjs/CdnjsProvider.cs
- src/LibraryManager/Providers/FileSystem/FileSystemProvider.cs
- src/LibraryManager/Providers/Unpkg/UnpkgCatalog.cs
- src/LibraryManager/Providers/Unpkg/UnpkgProvider.cs
- src/libman/Commands/UpdateCommand.cs
- test/LibraryManager.Mocks/Provider.cs
- test/LibraryManager.Test/LibraryIdToNameAndVersionConverterTest.cs
- test/LibraryManager.Test/LibraryInstallationStateTest.cs
- test/LibraryManager.Test/ManifestTest.cs
- test/LibraryManager.Test/Providers/Cdnjs/CdnjsCatalogTest.cs
- test/LibraryManager.Test/Providers/Cdnjs/CdnjsProviderTest.cs
- test/LibraryManager.Test/SimpleLibraryNamingSchemeTest.cs
- test/LibraryManager.Test/VersionedLibraryNamingSchemeTest.cs
- Introduce two naming schemes: Versioned and Simple
- Providers specify version support
- Based on provider either versioned or simple naming scheme is used
> Fix parsing of libraryId into name and version.

- src/LibraryManager.Vsix/Contracts/Dependencies.cs
We need to initialize naming schemes for the providers before we can proceed with any operation.
> Fix broken UI

- src/LibraryManager.Build/RestoreTask.cs
- src/LibraryManager.Vsix/Contracts/Logger.cs
- src/LibraryManager.Vsix/Json/TextviewCreationListener.cs
- src/LibraryManager.Vsix/Shared/LibraryCommandService.cs
- src/LibraryManager/Logging/LogMessageGenerator.cs
- src/LibraryManager/Manifest.cs
- src/LibraryManager/Resources/Text.Designer.cs
- src/LibraryManager/Resources/Text.resx
- src/libman/Commands/BaseCommand.cs
- src/libman/Commands/CleanCommand.cs
- src/libman/Commands/RestoreCommand.cs
- src/libman/Commands/UpdateCommand.cs
- test/LibraryManager.Test/ManifestTest.cs
- test/Microsoft.Web.LibraryManager.Build.Test/RestoreTaskTest.cs
This PR fixes bug #300 
We now call IEnumerable<ILibraryOperationResult> validationResults = await manifest.GetValidationResultsAsync() before all manifest operations. 
We report validation errors if there are any, otherwise proceed with the operation and Log the operation results.
This PR also improves log messages so they are consistent and accurate.
>  Reporting validation errors before calling operations

- src/LibraryManager.Contracts/Resources/Text.Designer.cs
- src/LibraryManager.Contracts/Resources/Text.resx
- test/libman.Test/BaseCommandTests.cs
Updated error message when manifest file has syntax errors
Note: @justcla signed off on the strings here: https://github.com/aspnet/LibraryManager/pull/319. Updating the test here
> Update error message when manifest file has syntax errors

- src/LibraryManager.Build/Microsoft.Web.LibraryManager.Build.csproj
This change is to include all dependencies of the msbuild task assembly in the package directory. 
Package contents after the change: <br/>
> Package all dependencies for Microsoft.Web.LibraryManager.Build

- Directory.Build.props
- LibraryManager.msbuild
- src/libman/libman.csproj
- src/libman/libman.nuspec
- tools/ShimGenerator/ShimGenerator.targets
Renames the CLI nuget package to `Microsoft.Web.LibraryManager.Cli`
Also fixes up NuGet properties for `Copyright` for all packages and `GitCommitId` for the CLI package.
> Cli rename

- src/LibraryManager.Vsix/UI/Models/InstallDialogViewModel.cs
- src/LibraryManager/Json/LibraryInstallationStateOnDisk.cs
- src/LibraryManager/LibraryNaming/LibraryIdToNameAndVersionConverter.cs
- src/LibraryManager/Properties/AssemblyInfo.cs
- test/LibraryManager.Mocks/HostInteraction.cs
- test/LibraryManager.Test/LibrariesValidatorTest.cs
- test/LibraryManager.Test/LibraryIdToNameAndVersionConverterTest.cs
- test/LibraryManager.Test/LibraryInstallationStateTest.cs
- test/LibraryManager.Test/ManifestTest.cs
- test/LibraryManager.Test/Providers/Cdnjs/CdnjsCatalogTest.cs
- test/LibraryManager.Test/Providers/FileSystem/FileSystemProviderTest.cs
- test/LibraryManager.Test/Providers/Unpkg/UnpkgProviderTest.cs
- test/Microsoft.Web.LibraryManager.Vsix.Test/Microsoft.Web.LibraryManager.Vsix.Test.csproj
- test/Microsoft.Web.LibraryManager.Vsix.Test/UI/Models/InstallDialogViewModelTest.cs
This addresses a regression from #326.  When we add a library through the
UI *and* the libman.json file is open in a text buffer, we serialize the
LibraryInstallationState directly.  LibraryInstallationState is no longer annotated for JSON serialization, so this causes us to insert invalid JSON into the manifest file.
> Fix serialization when using UI

- src/LibraryManager/Providers/jsDelivr/JsDelivrCatalog.cs
For GitHub only, the JSDeliver verison completion would cause the library name to be duplicated as the version completion contained the full library ID.  E.g. jquery/jquery@jquery/jquery@3.3.1.
> Only use the library version for version completion, not the full ID.

- src/LibraryManager/Providers/jsDelivr/JsDelivrProviderFactory.cs
Update dotnet framework version to 4.7.2 for JsDelivrProviderFactory
> Update dotnet framework version to 4.7.2 for JsDelivrProviderFactory

- test/Microsoft.Web.LibraryManager.Vsix.Test/JSONHelpersTest.cs
These tests work fine on my dev machine. I'm investigating why it fails on appveyor build. Temporarily disabling the tests so that we can get a green build.
> Disable tests to fix build break

- src/libman/Commands/BaseCommand.cs
- src/libman/Commands/InitCommand.cs
- src/libman/Commands/InstallCommand.cs
- src/libman/Contracts/ConsoleLogger.cs
- src/libman/EnvironmentSettings.cs
- src/libman/LibraryResolver.cs
- src/libman/Resources/Text.Designer.cs
- src/libman/Resources/Text.resx
- test/libman.Test/SampleTestCommand.cs
Fixes the issue where using the interactive commands (`libman init`/ `libman install`) appear to be hung if the console's input is redirected.
Visual studio's Package manager console is one such case.
> Disables interactive mode on consoles with redirected input

- src/LibraryManager.Vsix/Commands/CommandTable/LocalizationFiles/VSCommandTable.cs.xlf
- src/LibraryManager.Vsix/Commands/CommandTable/LocalizationFiles/VSCommandTable.de.xlf
- src/LibraryManager.Vsix/Commands/CommandTable/LocalizationFiles/VSCommandTable.en.xlf
- src/LibraryManager.Vsix/Commands/CommandTable/LocalizationFiles/VSCommandTable.es.xlf
- src/LibraryManager.Vsix/Commands/CommandTable/LocalizationFiles/VSCommandTable.fr.xlf
- src/LibraryManager.Vsix/Commands/CommandTable/LocalizationFiles/VSCommandTable.it.xlf
- src/LibraryManager.Vsix/Commands/CommandTable/LocalizationFiles/VSCommandTable.ja.xlf
- src/LibraryManager.Vsix/Commands/CommandTable/LocalizationFiles/VSCommandTable.ko.xlf
- src/LibraryManager.Vsix/Commands/CommandTable/LocalizationFiles/VSCommandTable.pl.xlf
- src/LibraryManager.Vsix/Commands/CommandTable/LocalizationFiles/VSCommandTable.pt-BR.xlf
- src/LibraryManager.Vsix/Commands/CommandTable/LocalizationFiles/VSCommandTable.ru.xlf
- src/LibraryManager.Vsix/Commands/CommandTable/LocalizationFiles/VSCommandTable.tr.xlf
- src/LibraryManager.Vsix/Commands/CommandTable/LocalizationFiles/VSCommandTable.zh-Hans.xlf
- src/LibraryManager.Vsix/Commands/CommandTable/LocalizationFiles/VSCommandTable.zh-Hant.xlf
- src/LibraryManager.Vsix/Commands/CommandTable/VSCommandTable.cs.vsct
- src/LibraryManager.Vsix/Commands/CommandTable/VSCommandTable.de.vsct
- src/LibraryManager.Vsix/Commands/CommandTable/VSCommandTable.es.vsct
- src/LibraryManager.Vsix/Commands/CommandTable/VSCommandTable.fr.vsct
- src/LibraryManager.Vsix/Commands/CommandTable/VSCommandTable.it.vsct
- src/LibraryManager.Vsix/Commands/CommandTable/VSCommandTable.ja.vsct
- src/LibraryManager.Vsix/Commands/CommandTable/VSCommandTable.ko.vsct
- src/LibraryManager.Vsix/Commands/CommandTable/VSCommandTable.pl.vsct
- src/LibraryManager.Vsix/Commands/CommandTable/VSCommandTable.pt-BR.vsct
- src/LibraryManager.Vsix/Commands/CommandTable/VSCommandTable.ru.vsct
- src/LibraryManager.Vsix/Commands/CommandTable/VSCommandTable.tr.vsct
- src/LibraryManager.Vsix/Commands/CommandTable/VSCommandTable.zh-Hans.vsct
- src/LibraryManager.Vsix/Commands/CommandTable/VSCommandTable.zh-Hant.vsct
It looks like the last time English VSCT file was updated, we updated XLF files and had that translated, but we haven't converted translated XLF files back into localized VSCT files. Localized VSCT files were either not translated at all or had stale translations in them. I updated all VSCT files, not just French. 
The path change in the XLF files is ignorable. Only VSCT changes really matter here. We should consider using github file URL rather than local repo path in the XLF files to avoid meaningless diffs like that.
> Updating localized VSCT files

- src/LibraryManager.Vsix/UI/Controls/Library.xaml.cs
Fix for https://devdiv.visualstudio.com/DevDiv/_workitems/edit/774500. 
For Chinese, the TextChanged event gets fired (claiming that the AddedLength is positive) even when the Text property hasn't changed yet. This is causing a null ref because of Text.
> Fixing Hang for Add Client-Side Library Window for CHS machines

- src/LibraryManager.Vsix/UI/Controls/Library.xaml
Bug is being tracked by:
[BUG 666417 - Fix accessibility bugs reported by Keros tool in LibraryManager project](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/666417)
> Fixed VSTS Bug 666417 by setting the popup's StaysOpen property to false

- src/LibraryManager.Contracts/ResourceDownloadException.cs
- src/LibraryManager/CacheService/CacheService.cs
- src/LibraryManager/CacheService/WebRequestHandler.cs
This attempts to address severe flakiness we've seen from all providers,
as well as in executing our unit tests.  Many of the failures we see are
intermittent 404s, so the loop gives us better resiliency when CDNs are
being flaky.
> Add retry loop when downloading content from providers.

- src/LibraryManager.Vsix/UI/Controls/PackageContentsTreeView.xaml
Set AutomationProperties.Name for TreeViewItem to fix issue reported by keros accessibility tool.
> Set AutomationProperties.Name for TreeViewItem

- src/LibraryManager.Vsix/Commands/InstallLibraryCommand.cs
- src/LibraryManager.Vsix/UI/InstallDialog.xaml.cs
Based on [Bug 790461](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/790461) it seems like `            bool isLibraryInstallationStateValid = await IsLibraryInstallationStateValidAsync().ConfigureAwait(false);
` on line 218 is switching to a background thread after it returns. In the `else` clause below we are accessing `ViewModel` which is a dependency property that requires us to be on the UI thread to access, which crashes VS.
> Fixing 790461 - Libman Install Dialog Install button crashes VS

- src/LibraryManager.Vsix/UI/Controls/Library.xaml.cs
- src/LibraryManager.Vsix/UI/Controls/TargetLocation.xaml.cs
When popup is open, and esc key is pressed, focus should remain in textbox. 
How was it tested?
- Ran existing unit and integration tests
> Handle esc key press event when popup is open

- src/LibraryManager.Vsix/UI/Controls/Library.xaml.cs
- src/LibraryManager.Vsix/UI/Controls/TargetLocation.xaml.cs
We want to be able to navigate to previous control when Shift+Tab is pressed when invoked from Library/TargetLocation controls
> Handle Shift+Tab correctly for Library and TargetLocation controls

- src/LibraryManager.Vsix/UI/Controls/Library.xaml
- src/LibraryManager.Vsix/UI/Controls/TargetLocation.xaml
- src/LibraryManager.Vsix/UI/InstallDialog.xaml
Added AutomationProperties.Name to completion items so that narrator reads the selected item instead of the class name.
Testing:
- Ran all unit and integration tests
> Added AutomationProperties.Name to completion items

- src/LibraryManager.Vsix/Microsoft.Web.LibraryManager.Vsix.csproj
- src/LibraryManager.Vsix/UI/Controls/Library.xaml
- src/LibraryManager.Vsix/UI/Controls/TargetLocation.xaml
- src/LibraryManager.Vsix/UI/Extensions/RemoveSubstringExtension.cs
- src/LibraryManager.Vsix/UI/InstallDialog.xaml
_ was added when access keys were implemented. This seems to interfere with narrator. Made changes to strip _ for automation names.
How was this tested:
- Unit and integration tests
> Changes to remove _ from library, target location and provider names when narrator is on

- src/LibraryManager.Vsix/Microsoft.Web.LibraryManager.Vsix.csproj
- src/LibraryManager.Vsix/Resources/Text.Designer.cs
- src/LibraryManager.Vsix/Resources/Text.resx
- src/LibraryManager.Vsix/UI/Controls/PackageContentsTreeView.xaml
- src/LibraryManager.Vsix/UI/Controls/PackageContentsTreeView.xaml.cs
- src/LibraryManager.Vsix/UI/Converters/CheckBoxAutomationNameConverter.cs
- src/LibraryManager.Vsix/UI/InstallDialog.xaml
Fixed following issues with this pr:
1. Made sure tree view items are non tabbable. User can tab into tree view and use up/down arrow keys to navigate
2. Home and end key press events work as expected
3. When treeview items are selected(via keyboard commands), screen reader should narrate checkbox status, folder status(expanded/collapsed), file name
4. When in choose specific mode , hitting right arrow key should expand node and left arrow should collapse node
5. When selected, treeview item text foreground color should be white
6. Hitting space should toggle treeview item selection
> Fix accessibility issue around PackageContentsTreeView control

- src/LibraryManager.Vsix/Microsoft.Web.LibraryManager.Vsix.csproj
The icon was not included in the VSIX because it was being embedded in the DLL.  This meant that the vsixmanifest was pointing at a non-existent file, and so VS would fall back to a default icon for LibMan's extension details.
This .png file isn't used elsewhere as an embedded resource; for the context menu items, we use an KnownImageMoniker instead.
> Fix icon to show in the Manage Extensions dialog

- build/PackageVersions.targets
- src/LibraryManager.Vsix/Commands/InstallLibraryCommand.cs
- src/LibraryManager.Vsix/Commands/ManageLibrariesCommand.cs
- src/LibraryManager.Vsix/Commands/RestoreOnBuildCommand.cs
- src/LibraryManager.Vsix/Contracts/Dependencies.cs
- src/LibraryManager.Vsix/Contracts/DependenciesFactory.cs
- src/LibraryManager.Vsix/Contracts/IDependenciesFactory.cs
- src/LibraryManager.Vsix/Json/Completion/FilesCompletionProvider.cs
- src/LibraryManager.Vsix/Json/Completion/LibraryIdCompletionProvider.cs
- src/LibraryManager.Vsix/Json/Completion/PathCompletionProvider.cs
- src/LibraryManager.Vsix/Json/Completion/ProviderCompletionProvider.cs
- src/LibraryManager.Vsix/Json/SuggestedActions/SuggestedActionProvider.cs
- src/LibraryManager.Vsix/Json/SuggestedActions/UpdateSuggestedAction.cs
- src/LibraryManager.Vsix/Json/SuggestedActions/UpdateSuggestedActionSet.cs
- src/LibraryManager.Vsix/Json/TextviewCreationListener.cs
- src/LibraryManager.Vsix/LibraryManagerPackage.cs
- src/LibraryManager.Vsix/Microsoft.Web.LibraryManager.Vsix.csproj
- src/LibraryManager.Vsix/Properties/AssemblyInfo.cs
- src/LibraryManager.Vsix/Shared/DefaultSolutionEvents.cs
- src/LibraryManager.Vsix/Shared/LibraryCommandService.cs
- src/LibraryManager.Vsix/UI/InstallDialog.xaml.cs
- test/LibraryManager.IntegrationTest/FileSaveRestoreTests.cs
- test/LibraryManager.IntegrationTest/Helpers/FileIOHelper.cs
- test/LibraryManager.IntegrationTest/SuggestedActionTests.cs
- test/LibraryManager.IntegrationTest/VisualStudioLibmanHostTests.cs
- test/LibraryManager.Mocks/HostInteraction.cs
- test/Microsoft.Web.LibraryManager.Vsix.Test/Microsoft.Web.LibraryManager.Vsix.Test.csproj
- test/Microsoft.Web.LibraryManager.Vsix.Test/Shared/LibraryCommandServiceTest.cs
This fixes a simple issue (one line, swapping order of parameters) which fixes #441.  Adding a unit test to cover this led to many other changes.
This is also a pre-req to fixing #306, which was filed before the regression was introduced.
> Uninstall LightBulb fails to remove files

- src/LibraryManager.Vsix/Commands/CommandTable/VSCommandTable.en.vsct
VSCommandTable.en.vsct got messed up and all entries for "en" got replaced by "cs" during loc handback:
https://github.com/aspnet/LibraryManager/pull/464/files
Fixing it up.
> Fix issues in en vsct

- src/LibraryManager.Vsix/Json/JsonHelpers.cs
- test/LibraryManager.IntegrationTest/SuggestedActionTests.cs
- test/Microsoft.Web.LibraryManager.Vsix.Test/JSONHelpersTest.cs
- test/libman.Test/LibmanInstallTest.cs
- test/libman.Test/LibmanUpdateTest.cs
When we deserialize these values using VS' JSON parser, it adds an extra
level of escaping to the backslashes.  We need to compensate for this when we
compare with values from the LibMan manifest.
This fixes #363 and #306.
> Fix deserialization of backslashes from VS editor

- src/LibraryManager/Providers/Unpkg/UnpkgCatalog.cs
- test/LibraryManager.Test/Providers/Unpkg/UnpkgCatalogTest.cs
Issue description:
- Invoke libman UI
- Select ‘unpkg’ in the provider combo
- Type ‘@’ character in the ‘Library’ text box.
- Hit cancel button
You will notice that dialog doesn't close. Made a change as a part of this pr to not throw null ref exception and close the dialog when cancel button is hit.
How was this tested?
- Ran existing unit and integration tests
- Added unit test for this scenario
> [UI] Fix issue with cancel button for unpkg provider

- src/LibraryManager.Vsix/UI/Controls/TextBoxWithSearch.xaml
- src/LibraryManager.Vsix/UI/Controls/TextBoxWithSearch.xaml.cs
- src/LibraryManager.Vsix/UI/Models/SearchTextBoxViewModel.cs
- src/LibraryManager.Vsix/UI/Models/TargetLocationViewModel.cs
This addresses 2 accessibility issues:
1. When a user dismisses completion, or types a search text that doesn't match any completions, then hits tab, we will commit the last partially-matching completion item that we remembered from the session.  This can be a very bad experience, as we overwrite a value that the user typed in.
2. When we commit library names, 2 fields are changed but there is no indication given to a screen reader.  After these changes, we will notify when completions are committed (so the user knows the completed value), and also when changing the library name causes the Target Location to be updated.
> Improve accessibility for committing completions in Install Dialog

- src/LibraryManager.Vsix/UI/Models/InstallDialogViewModel.cs
This fixes an error dialog that pops up when clicking the Install button saying the destination was undefined.  It was a missed cleanup during the ViewModel refactoring.
> Remove unused property for install package location

- src/LibraryManager.Vsix/Resources/Text.Designer.cs
- src/LibraryManager.Vsix/Resources/Text.resx
- src/LibraryManager.Vsix/UI/Controls/PackageContentsTreeView.xaml
- src/LibraryManager.Vsix/UI/Controls/PackageContentsTreeView.xaml.cs
- src/LibraryManager.Vsix/UI/Converters/CheckBoxAutomationNameConverter.cs
- src/LibraryManager.Vsix/UI/InstallDialog.xaml
- src/LibraryManager.Vsix/UI/InstallDialog.xaml.cs
- src/LibraryManager.Vsix/UI/Models/PackageItem.cs
- test/Microsoft.Web.LibraryManager.Vsix.Test/UI/Converters/CheckBoxAutomationNameConverterTests.cs
Changes in this pr include:
- Tabbing into treeView will not set focus and select the first item 
- Updated CheckBoxNameAutomationConverter to include Intermediate state of checkBox. Also made changes so that narrator specifies whether folder/file is selected
- Reduce border thickness
- TreeView should is not accessible when IncludeAllLibraryFiles option is selected
- Added new resource strings
- Added unit tests for CheckBoxNameAutomationConverter
> [UI] Fix accessibility issues in treeView

- src/LibraryManager.Vsix/UI/Controls/TextBoxWithSearch.xaml.cs
Apprently throwing unhandled exception from event handlers (at least from this one) leave WPF in a bad state. Not sure what's a good generic way of handling it, but this fix addresses the forward slash issue (in that case we were getting CompletionSet struct with Completion list set to null). Also removing a check for null of the struct itself. It's a struct. That method will always return false.
> Fix for #395 (internally tracked as Bug 936856)

- src/LibraryManager.Contracts/FileHelpers.cs
Fixes issue #475. The problem here was that we first write downloaded library to a temp file, and then copy it to the final destination. That by itself is fine, but on Linux and MacOS Path.GetTempFileName() create a temp file with permission 600, which causes issues on publishing (since read permission is missing for everyone other than the owner). Working around it by creating and writing to a slightly modified temp file name that will still be unique, but wasn't originally created as a temp file by mkstemps, so it won't have 600 permissions and instead will have the desired 664 permissions.
> Fixes file permission issues on Linux and MacOS

- src/LibraryManager/Helpers/Extensions.cs
- src/LibraryManager/Providers/Unpkg/UnpkgCatalog.cs
- src/LibraryManager/Providers/Unpkg/UnpkgProvider.cs
- src/LibraryManager/Providers/jsDelivr/JsDelivrCatalog.cs
- src/LibraryManager/Providers/jsDelivr/jsDelivrProvider.cs
- test/LibraryManager.Mocks/WebRequestHandler.cs
- test/LibraryManager.Test/Providers/JsDelivr/JsDelivrCatalogTest.cs
- test/LibraryManager.Test/Providers/Unpkg/UnpkgCatalogTest.cs
This change is a beginning to make the unit tests reliable and consistent, without relying upon web requests to external resources beyond our control.  It's just a first pass, as the full set of changes needed are very broad.
> Refactor UnkpgCatalog and JsDelivrCatalog for testability

- src/LibraryManager.Build/Microsoft.Web.LibraryManager.Build.targets
The targets file uses relative paths which is not working for projects using `packages.config`. This PR fixes #500
> Corrected relative paths of tools dll in targets (fixes #500)

- src/LibraryManager.Vsix/UI/Models/LibraryIdViewModel.cs
- test/Microsoft.Web.LibraryManager.Vsix.Test/UI/Models/LibraryIdViewModelTests.cs
This fixes LibraryIdViewModel.FilterCompletions not returning any completions for scoped packages.
> Fixing version completion for scoped packages

- test/Microsoft.Web.LibraryManager.Vsix.Test/UI/Models/LibraryIdViewModelTests.cs
Here if the `caretIndex`  is at 13 (the end of the string), making `GetCompletionSetAsync `filter all completions that start with `@types/test@2`, so there should only be 1 result.
Fixing the scenario so it's correctly filtering on completions starting with `@types/test@` and contain "2" in the version.
Silly me, don't know why I didn't run all unit tests again before merging my previous PR...
> Fixing a bad test in LibraryIdViewModelTests

- src/LibraryManager.Vsix/UI/Controls/TextBoxWithSearch.xaml.cs
Having TextBoxWithSearch.SearchTextBox_TextChanged not block the UI thread when possible to avoid hangs from slow network connections and improve general responsiveness.
This hopefully fixes [this issue](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/972655)
> Fixing a hang from TextBoxWithSearch.SearchTextBox_TextChanged from slow network connections

- LibraryManager.msbuild
- build/analyzers/rulesets/Default.ruleset
- src/LibraryManager.Vsix/Contracts/Logger.cs
- src/LibraryManager.Vsix/Json/Completion/CompletionController.cs
- src/LibraryManager.Vsix/Json/Completion/FilesCompletionProvider.cs
- src/LibraryManager.Vsix/Json/Completion/LibraryIdCompletionProvider.cs
- src/LibraryManager.Vsix/Json/SuggestedActions/UninstallSuggestedActions.cs
- src/LibraryManager.Vsix/Json/SuggestedActions/UpdateSuggestedAction.cs
- src/LibraryManager.Vsix/Json/SuggestedActions/UpdateSuggestedActionSet.cs
- src/LibraryManager.Vsix/Json/TextviewCreationListener.cs
- src/LibraryManager.Vsix/Microsoft.Web.LibraryManager.Vsix.csproj
- src/LibraryManager/SemanticVersion/SemanticVersion.cs
- src/libman/GlobalSuppressions.cs
- test/LibraryManager.IntegrationTest/Services/InstallDialogTestService.cs
This addresses the remaining code analysis failures.  There are still a few MSBuild warnings left, but this significantly improves our code cleanliness in the editor/IDE.
> Fix code warnings from analyzers

- src/libman/runtimeconfig.template.json
This enables the CLI tool to continue to work on images which only have versions newer than netcoreapp2.1.
In the future if a breaking change is made that breaks us on roll-forward, we'll have to multi-target the project to that framework.  It's not worthwhile to multi-target for every new version and have to ship just to keep in lockstep though.
This fixes #520
> Enable roll-forward on major versions for CLI tool

- src/LibraryManager.Build/Microsoft.Web.LibraryManager.Build.csproj
- src/LibraryManager.Build/RestoreTask.cs
This addresses a recurring issue where doing a WebDeploy-based publish from within Visual Studio encounteres MissingMethodExceptions when running LibMan's Restore-on-build.  The issue is that VS Publish runs MSBuild in-proc, so it loads the build task DLL from the NuGet package, but the other LibMan assemblies are already loaded into the VS appdomain from the VSIX (often a newer version).  Any incompatibilities between these cause the build task to throw.
This fix causes the build task to be executed in its own appdomain, and as such it resolves all of its dependent assemblies from the nuget package.  The appdomain gets cleared when the build is finished, so we're not leaving duplicates of all the assmeblies loaded into VS.  Note: the Build task DLL itself is loaded into VS' primary …
> Make the restore-on-build task run in its own app-domain

- test/Microsoft.Web.LibraryManager.Vsix.Test/Microsoft.Web.LibraryManager.Vsix.Test.csproj
Moq has a dependency on System.Threading.Tasks.Extensions 4.2.0.0, but our dependency graph pulls in 4.2.0.1 (gee thanks, whoever bumped that).  Setting the binding redirect in the test project fixes it at runtime.
This was likely a regression caused in c5beab72, when we bumped up the version of Microsoft.VisualStudio.Threading (which seems to be at least one source of the 4.2.0.1 transitive dependency).
> Workaround an assembly version conflict

- src/LibraryManager/CacheService/CacheService.cs
This fixes #511, so that downloaded files do not get included in user
profile roaming.
> Move the file cache to %LocalAppData%

- build/PackageVersions.targets
- src/LibraryManager/Microsoft.Web.LibraryManager.csproj
- src/LibraryManager/Providers/BaseProvider.cs
- src/LibraryManager/Providers/Cdnjs/CdnjsProvider.cs
- src/LibraryManager/Providers/Cdnjs/CdnjsProviderFactory.cs
- src/LibraryManager/Providers/FileSystem/FileSystemProvider.cs
- src/LibraryManager/Providers/Unpkg/UnpkgProvider.cs
- src/LibraryManager/Providers/Unpkg/UnpkgProviderFactory.cs
- src/LibraryManager/Providers/jsDelivr/JsDelivrProviderFactory.cs
- src/LibraryManager/Providers/jsDelivr/jsDelivrProvider.cs
- src/LibraryManager/Utilities/FileGlobbingUtility.cs
- test/LibraryManager.Test/Configuration/SettingsTest.cs
- test/LibraryManager.Test/Providers/Cdnjs/CdnjsProviderTest.cs
- test/LibraryManager.Test/Providers/FileSystem/FileSystemProviderTest.cs
- test/LibraryManager.Test/Providers/JsDelivr/JsDelivrProviderTest.cs
- test/LibraryManager.Test/Providers/Unpkg/UnpkgProviderTest.cs
- test/LibraryManager.Test/TestUtilities/StringUtility.cs
- test/LibraryManager.Test/Utilities/FileGlobbingUtilityTests.cs
- test/libman.Test/LibmanCacheCleanTests.cs
- version.json
This change adds support for file patterns (`*.js`, or `**/*.css`, or even negations like `!*.map`) in the libman.json file.  This has been a top requested feature since day 1.
File pattern support is a pretty big behavioral change (even if the diff is small).  While it is technically a breaking change (e.g. a file named `*.js` will now be expanded), I doubt it will actually impact anyone negatively.  It is easier though with the version bump to say that file patterns are supported on 2.1+ instead of 2.0.113+ (or whatever the actual release version is).
> Add support for file patterns in libman.json

- src/LibraryManager/CacheService/CacheService.cs
- src/LibraryManager/Providers/BaseProvider.cs
- src/LibraryManager/Resources/Text.Designer.cs
- src/LibraryManager/Resources/Text.resx
- src/LibraryManager/Utilities/ParallelUtility.cs
- test/LibraryManager.Test/CacheServiceTest.cs
- test/LibraryManager.Test/Utilities/ParallelUtilityTests.cs
Attempting to address poor performance when restoring libraries (such as #389 and #512).  There are two parts to this change:
1. Introducing parallel downloads when populating the file cache.  Until now, we have downloaded files in serial order, which is very slow.  With these changes, we will allow up to 10 simultaneous requests for files (slightly more than most browsers).  Keeping the limit is important to avoid DDoSing a server, and to avoid queuing too many TPL tasks or exploding the load on the thread pool.
2. Adding new output messages showing when files are being downloaded.  This mitigates the perception that libman is hung by reporting progress more regularly throughout the operation.
> Download files in parallel

- src/LibraryManager.Build/Contracts/HostInteraction.cs
- src/LibraryManager.Contracts/FileHelpers.cs
- src/LibraryManager.Contracts/IHostInteraction.cs
- src/LibraryManager.Vsix/Contracts/HostInteraction.cs
- src/LibraryManager/Providers/BaseProvider.cs
- src/libman/Contracts/HostInteraction.cs
- test/LibraryManager.Mocks/HostInteraction.cs
- test/libman.Test/Mocks/HostInteractionInternal.cs
Compared to the original implementation of reading files in from the cache and writing them back out to the destination, a simple file copy seems to be several times faster on average.
> Make restore faster by copying files

- src/LibraryManager.Contracts/PredefinedErrors.cs
- src/LibraryManager.Contracts/Resources/Text.Designer.cs
- src/LibraryManager.Contracts/Resources/Text.resx
- src/LibraryManager/Providers/BaseProvider.cs
This came up during the PR review for #534 but we held off at the time due to the new localized string.
> Add a better message if a file entry has an empty name

- src/LibraryManager.Contracts/Caching/ICacheService.cs
- src/LibraryManager/CacheService/CacheService.cs
- src/LibraryManager/Providers/BaseProvider.cs
- src/LibraryManager/Providers/Cdnjs/CdnjsCatalog.cs
- src/LibraryManager/Providers/Cdnjs/CdnjsProvider.cs
- test/LibraryManager.Mocks/CacheServices/FakeCdnjsCacheService.cs
- test/LibraryManager.Test/Providers/Cdnjs/CdnjsCatalogTest.cs
- test/LibraryManager.Test/Providers/Cdnjs/CdnjsProviderTest.cs
Some of the Cdnjs unit tests were still using live web requests.  When the requests started returning different data, it changed the behavior (as far as the unit tests' expectations were concerned).  This PR refactors some of the code so that we can mock out the requests to control the data coming back. and thereby make sure that the unit tests are testing against a consistent data set.
> Fixup 2 failing Cdnjs unit tests

- build/PackageVersions.targets
- test/LibraryManager.IntegrationTest/LibmanCompletionTests.cs
Several of these tests were encountering issues where VS's auto-format would interfere with the contents being typed.
I also updated the version of the VS test framework (Apex) used to the latest available package.
> Fix VS integration tests

- README.md
People need to know that libman works with more than just cdnjs.
- Add jsdelivr and unpkg as providers.
> Update providers in README

- src/LibraryManager.Contracts/MultilingualResources/Microsoft.Web.LibraryManager.Contracts.cs.xlf
- src/LibraryManager.Contracts/MultilingualResources/Microsoft.Web.LibraryManager.Contracts.de.xlf
- src/LibraryManager.Contracts/MultilingualResources/Microsoft.Web.LibraryManager.Contracts.es.xlf
- src/LibraryManager.Contracts/MultilingualResources/Microsoft.Web.LibraryManager.Contracts.fr.xlf
- src/LibraryManager.Contracts/MultilingualResources/Microsoft.Web.LibraryManager.Contracts.it.xlf
- src/LibraryManager.Contracts/MultilingualResources/Microsoft.Web.LibraryManager.Contracts.ja.xlf
- src/LibraryManager.Contracts/MultilingualResources/Microsoft.Web.LibraryManager.Contracts.ko.xlf
- src/LibraryManager.Contracts/MultilingualResources/Microsoft.Web.LibraryManager.Contracts.pl.xlf
- src/LibraryManager.Contracts/MultilingualResources/Microsoft.Web.LibraryManager.Contracts.pt-BR.xlf
- src/LibraryManager.Contracts/MultilingualResources/Microsoft.Web.LibraryManager.Contracts.ru.xlf
- src/LibraryManager.Contracts/MultilingualResources/Microsoft.Web.LibraryManager.Contracts.tr.xlf
- src/LibraryManager.Contracts/MultilingualResources/Microsoft.Web.LibraryManager.Contracts.zh-Hans.xlf
- src/LibraryManager.Contracts/MultilingualResources/Microsoft.Web.LibraryManager.Contracts.zh-Hant.xlf
- src/LibraryManager/Resources/Text.cs.resx
- src/LibraryManager/Resources/Text.de.resx
- src/LibraryManager/Resources/Text.es.resx
- src/LibraryManager/Resources/Text.fr.resx
- src/LibraryManager/Resources/Text.it.resx
- src/LibraryManager/Resources/Text.ja.resx
- src/LibraryManager/Resources/Text.ko.resx
- src/LibraryManager/Resources/Text.pl.resx
- src/LibraryManager/Resources/Text.pt-BR.resx
- src/LibraryManager/Resources/Text.ru.resx
- src/LibraryManager/Resources/Text.tr.resx
- src/LibraryManager/Resources/Text.zh-Hans.resx
- src/LibraryManager/Resources/Text.zh-Hant.resx
- src/libman/Resources/Text.fr.resx
- src/libman/Resources/Text.pt-BR.resx
- src/libman/Resources/Text.tr.resx
- src/libman/Resources/Text.zh-Hant.resx
* Updated resx files from previous handback (forgot that step, MAT is a little weird to use the first time)
* Found a new string that was never generated into XLF files.  Now it will be included the next time we do a localization pass.
> Localization updates

- src/LibraryManager.Contracts/Microsoft.Web.LibraryManager.Contracts.csproj
System.Runtime was removed in netstandard20, so this reference could not
be resolved.
> Fix warning on Dependencies node in VS

- src/LibraryManager.Build/RestoreTask.cs
Currently, we show all libman build messages as Important, which means
that every detail comes through even when using /verbosity:minimal.
With this change, most messages will be shown only in normal/detailed
verbosity.  We will still show the opening and closing lines for when we
start and complete restore for minimal verbosity.
> Make build task messages not important by default

- src/LibraryManager/Providers/Unpkg/UnpkgProvider.cs
- src/LibraryManager/Providers/jsDelivr/jsDelivrProvider.cs
- test/LibraryManager.Test/Providers/JsDelivr/JsDelivrProviderTest.cs
- test/LibraryManager.Test/Providers/Unpkg/UnpkgProviderTest.cs
In some contexts, notably ASP.NET Razor, the @@ escape sequence wasn't
supported in tag attributes (such as <script src="lib/@@foo"/>).
Removing the @ sign avoids the headache when this issue is encountered.
Scoped packages will still be pathed uniquely, just without the @
prefix.
This addresses https://developercommunity.visualstudio.com/content/problem/923113/signalr-issue-with.html.
> Remove '@' from recommended installation path

- azure-pipelines.yml
- src/Directory.Build.targets
MAT needn't run on CI builds (resources should change there).  It should
still run by default on dev machines, but this switch can also be used
to turn it off when it's being annoying.  This should save us a bunch of
warnings in the build output.
> Add a flag to disable the Multilingual App Toolkit

- azure-pipelines/official.yml
This is separate from the PR/CI pipeline, as it needs to run in a different pool.  The build logic was already extracted to be shared in build.yml.
> Create a pipeline for internal builds

- build/PackageVersions.targets
In VS 16.6 there is a breaking change that requires a VSSDK version of 16.5
or newer.
> Increment VSSDK build tools version

- src/LibraryManager.Build/Microsoft.Web.LibraryManager.Build.csproj
For netstandard project, the default behavior does not copylocal
dependencies from reference packages, and does not include them in the
package.  For Newtonsoft.Json, the dependency was resolved at runtime
from the SDK install path, so we never noticed it was missing.
Since we added Minimatch.dll for the file globs, it is not being
resolved when building through the .NET sdk (dotnet build).  This is
causing the build to fail with a LIB000 error (unknown failure).
The fix is to be more precise about what files we do include in the
package.  This also addresses the inconsistency about having these
assemblies in the build output path when signing package contents.
> Explicitly include runtime dependencies in Build package

- Directory.Build.props
- azure-pipelines/azure-pipeline.microbuild.after.yml
- azure-pipelines/azure-pipeline.microbuild.before.yml
- azure-pipelines/build.yml
- build/CreateInsertionMetadata.proj
- build/MicroBuild.Plugins.props
- setup/Microsoft.Web.LibraryManager.vsmanproj
This PR contains the plumbing necessary to insert VSIX builds into the Visual Studio product (which will be done from an internal pipeline).  Namely:
- Creates a .vsman file
- Pushes the .vsman file and the .vsix to the VSTS Drop
- Creates a file containing variables that are easily calculated here (like build versions) but which need to be consumed in the pipeline.
> Create VS Installer manifest and setup for pipeline insertion to VS

- build.cmd
- src/libman/Commands/CacheListCommand.cs
- src/libman/Resources/Text.Designer.cs
- src/libman/Resources/Text.resx
- test/libman.Test/LibmanCacheListTest.cs
I only applied this to the 'cache list' command, as that's used when a user is looking to find the cache contents.
Fixes #234.
> Include the cache location in 'libman cache list'

- test/libman.Test/LibmanInstallTest.cs
- test/libman.Test/LibmanUpdateTest.cs
Ideally these wouldn't make any live web requests, but we don't have that level of DI built into the CLI commands yet (or their tests) yet.  Using specific versions will still test the scenarios, but we won't have tests break whenever a new jQuery release is published.
> Make tests less prone to breaking when jQuery releases.

- src/LibraryManager/Providers/Cdnjs/CdnjsCatalog.cs
- src/LibraryManager/Providers/jsDelivr/JsDelivrCatalog.cs
- test/LibraryManager.Test/Providers/Cdnjs/CdnjsCatalogTest.cs
- test/LibraryManager.Test/Providers/JsDelivr/JsDelivrCatalogTest.cs
Cdnjs changed the ordering when they report package versions, so we need to correctly search for the latest.  (Ironically, our test mock data was already setup for this, but we didn't test it correctly.)
The JsDelivrCatalog implementation never handled prerelease versions, nor did it handle versions at all for GitHub releases.  These were both added.
Unpkg curently doesn't expose package versions via an API that we can easily consume (it's available, but as JSON content embedded in an HTML page... ew) so it was not changed as a part of this.
This change should address https://developercommunity.visualstudio.com/content/problem/1167156/check-for-updates-quick-action-broken-in-libmanjso.html
> Fix latest prerelease version for Cdnjs and JSDelivr

- src/libman/Commands/CacheCleanCommand.cs
- test/libman.Test/LibmanCacheCleanTests.cs
If a provider is given and it is not one of the available providers, output an invalid operation message like "Provider 'foo' is not installed.
Addresses #134
> fix: provide error message for unknown provider.

- Directory.Packages.props
- nuget.config
- src/LibraryManager.Vsix/Commands/InstallLibraryCommand.cs
- src/LibraryManager.Vsix/Commands/RestoreCommand.cs
- src/LibraryManager.Vsix/Commands/RestoreOnBuildCommand.cs
- src/LibraryManager.Vsix/Microsoft.Web.LibraryManager.Vsix.csproj
- src/LibraryManager.Vsix/Shared/LibraryCommandService.cs
The most temporary of these is the Nuget.VisualStudio package, which is
on its own feed.  Once the NuGet team can fully publish their changes,
it should be published again on the dotnet-public feed, and we can clean
it up from our nuget.config at that time.
> Changes for consuming merged interop assemblies in Dev17

- src/LibraryManager.Build/Microsoft.Web.LibraryManager.Build.targets
Addresses #644 and
https://developercommunity2.visualstudio.com/t/Live-Unit-Testing-build-with-failures-M/1268950
> Don't do restore during Live Unit Testing builds

- src/LibraryManager.Vsix/Resources/Text.Designer.cs
- src/LibraryManager.Vsix/Resources/Text.resx
- src/LibraryManager/Resources/Text.Designer.cs
- src/LibraryManager/Resources/Text.resx
The ellipsis should be used to indicate things which are still in
progress, not things which have completed.  In most cases, this was used
in a string like "X started...".
It would be acceptable to use "Starting X..." as that is the present
progressive tense, but we can also simply remove the ellipsis without
having to re-translate a bunch of strings.
Addresses #212
> Remove "..." for past tense strings

- src/LibraryManager.Vsix/UI/Controls/TextBoxWithSearch.xaml.cs
- src/LibraryManager.Vsix/UI/Models/LibraryIdViewModel.cs
- src/LibraryManager.Vsix/UI/Models/SearchTextBoxViewModel.cs
- test/Microsoft.Web.LibraryManager.Vsix.Test/UI/Models/LibraryIdViewModelTests.cs
There isn't a guarantee that the data from providers is sorted in the
desired order (e.g. for versions, sorted descending).  This change
ensures we sort the completion items before showing them in the search
box flyout.
In the JSON completion scenario (which is similar), each completion item
is instead represented by a CompletionEntry implementation which
implements IComparable<T> for that completion type.  The editor
completion stack handles the sorting for us already.
Fixes #531.
> Ensure completions in Add wizard are sorted

- src/LibraryManager.Vsix/UI/Controls/TextBoxWithSearch.xaml.cs
Currently we only update when new text is added, but this means that
typing an extra character may filter out a desired item, and then
deleting the character will not show the item.
> When deleting text in the search box, update item filter

- src/LibraryManager.Vsix/UI/Controls/TextBoxWithSearch.xaml
- src/LibraryManager.Vsix/UI/Controls/TextBoxWithSearch.xaml.cs
- src/LibraryManager.Vsix/UI/Theming/VsThemedComboBox.xaml
It's been a long-time issue that the completion popup on the search box
is not aligned with the left side of the completion window.  Originally
it was attempting to align with the cursor position, but the offsets
were calculated very incorrectly.
Aligning with the caret is hard, and also not entirely desirable.
Ideally, we would align with an inflection point for the completion
session (e.g. on for library ID, it would either align with the name or
with the start of the version; for target location, it would align with
the current path segment).
This is hard to do generically since we have no idea where the
inflection points are.  So, settling for left-alignment is still better
than being oddly not quite right aligned.
This also removes the attempt to move the offset with cursor movement, …
> Align combo box popup with left edge

- src/LibraryManager.Vsix/Commands/CommandTable/VSCommandTable.cs.vsct
- src/LibraryManager.Vsix/Commands/CommandTable/VSCommandTable.de.vsct
- src/LibraryManager.Vsix/Commands/CommandTable/VSCommandTable.en.vsct
- src/LibraryManager.Vsix/Commands/CommandTable/VSCommandTable.es.vsct
- src/LibraryManager.Vsix/Commands/CommandTable/VSCommandTable.fr.vsct
- src/LibraryManager.Vsix/Commands/CommandTable/VSCommandTable.it.vsct
- src/LibraryManager.Vsix/Commands/CommandTable/VSCommandTable.ja.vsct
- src/LibraryManager.Vsix/Commands/CommandTable/VSCommandTable.ko.vsct
- src/LibraryManager.Vsix/Commands/CommandTable/VSCommandTable.pl.vsct
- src/LibraryManager.Vsix/Commands/CommandTable/VSCommandTable.pt-BR.vsct
- src/LibraryManager.Vsix/Commands/CommandTable/VSCommandTable.ru.vsct
- src/LibraryManager.Vsix/Commands/CommandTable/VSCommandTable.tr.vsct
- src/LibraryManager.Vsix/Commands/CommandTable/VSCommandTable.zh-Hans.vsct
- src/LibraryManager.Vsix/Commands/CommandTable/VSCommandTable.zh-Hant.vsct
This shows up when right-clicking the project or any folder.  It's the
same command as mapped in the project Add menu, it's just duplicated in
the wrong placement.
Resolves #222.
> Remove extra "Client Side Library" menu item in WSP

- src/libman/Commands/CacheListCommand.cs
This flag didn't offer any behavior so it should just be removed.
Resolves #127.
> Remove '--libraries' flag from cache list command

- src/LibraryManager.Vsix/UI/Models/InstallDialogViewModel.cs
- src/LibraryManager/Manifest.cs
The default behavior when adding a library, if the defaultProvider was
not yet set, was to promote the new library's provider as the default.
This requires multiple edits to the file.  When the document is open in
the editor, we only calculate the edit for inserting the library.
This change does imply that adding via the UI wizard will have a
different output than using the CLI.  At least we'll no longer generate
an invalid manifest.  We may want to consider a more advanced edit
generation such that we apply both edits instead.
Resolves #393.
> Ensure that libraries added via wizard set the provider

- src/LibraryManager/Providers/Unpkg/UnpkgCatalog.cs
- test/LibraryManager.Test/Providers/Unpkg/UnpkgCatalogTest.cs
The API call used by the Unpkg catalog only returns the latest release
version.  In order to get prerelease versions as well (e.g. for the
Upgrade lightbulb), we need to specifically get all versions.
Resolves #349.
> Support prerelease versions from Unpkg

- src/LibraryManager/Resources/Text.resx
Some recent translations reverted these terms back to English.  This comment should clarify the expectation for future translations.
> Add comment to indicate terms which should be localized

- test/LibraryManager.Test/Microsoft.Web.LibraryManager.Test.csproj
- test/Microsoft.Web.LibraryManager.Build.Test/Microsoft.Web.LibraryManager.Build.Test.csproj
- test/libman.Test/libman.Test.csproj
As netcore2.1 is out of support, these tests fail to run on the CI
agents.  Updating to net6.0 will allow the tests to continue running.
Updating the src projects to net6.0 would also mean that they would stop
functioning for customers who did not have net6.0 installed.  This can
be a concern for both the MSBuild package and the CLI.  Such a change
should only be made when we are bumping the major version.
> Update unit tests to target net6.0

- src/LibraryManager.Vsix/UI/Controls/TextBoxWithSearch.xaml
- src/LibraryManager.Vsix/UI/Controls/TextBoxWithSearch.xaml.cs
Not sure why the old offset was calculated like that, it's as though the flyout had used `Placement="Right"` in XAML instead of `Placement="Left"`.
Resolves https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1468930
> Correct the aligment of the completion flyout

- src/LibraryManager/Providers/Cdnjs/CdnjsCatalog.cs
- test/LibraryManager.Test/CacheServiceTest.cs
- test/LibraryManager.Test/Providers/Cdnjs/CdnjsCatalogTest.cs
The Cdnjs API is changing to stop including the assets for all versions of a library in the /libraries/:library API.  We were using this to determine both library versions and library files.
The changes are fairly straightforward:
- for versions, we can just use the "versions" property from the library.  It's probably easier than what we were doing before (parsing each version from an "assets" entry).
- for files, we need to invoke the /libraries/:library/:version API instead.  However, the default file (which we use for selecting the default checked box in the wizard) is on the library group, not the library-version, so we still need to get that from the first request.
- Lastly, I included fields on each API call, so that we're not downloading any data that we aren't intending to use. …
> Adapt to Cdnjs API changes

- azure-pipelines/build.yml
- test/LibraryManager.Test/Microsoft.Web.LibraryManager.Test.csproj
- test/Microsoft.Web.LibraryManager.Build.Test/Microsoft.Web.LibraryManager.Build.Test.csproj
- test/libman.Test/libman.Test.csproj
Netsdk 6 requires MSBuild 17 (the VS2022) version.  It was already present on the PR build pipeline, but for the official signed CI builds the agent machines only have VS2019.
> Use netsdk 5 for the VS2019 build

- src/LibraryManager/Manifest.cs
- src/LibraryManager/Providers/Cdnjs/CdnjsCatalog.cs
- test/LibraryManager.Test/Microsoft.Web.LibraryManager.Test.csproj
- test/LibraryManager.Test/Providers/Cdnjs/CdnjsCatalogTest.cs
- test/LibraryManager.Test/Providers/Cdnjs/CdnjsProviderTest.cs
- test/LibraryManager.Test/Providers/FileSystem/FileSystemCatalogTest.cs
- test/Microsoft.Web.LibraryManager.Build.Test/Microsoft.Web.LibraryManager.Build.Test.csproj
- test/libman.Test/LibmanCacheCleanTests.cs
- test/libman.Test/LibmanInstallTest.cs
- test/libman.Test/LibmanUpdateTest.cs
- test/libman.Test/libman.Test.csproj
There are two main parts to this change:
* Tests rely on live data from the cdnjs catalog, so they were outdated and expecting old versions.  I didn't rectify this, merely updated them to pass again.  There was a lot of refactoring effort put in after this branch snapped to address this, but it's not worth the effort or risk to backport for servicing this release.
* Cdnjs version sort order changed.  This was originally addressed in #606 in trunk.  I also incorporated the change in #429 to simply use the specified current version for non-prereleases.  This affected how we calculate the "latest" version for new library defaults or for updates.
> Get tests passing

- src/LibraryManager.Vsix/ErrorList/ErrorListPropagator.cs
- src/LibraryManager.Vsix/Json/TextviewCreationListener.cs
File.ReadLines is implemented with an iterator that opens a stream to the file.  We were iterating it several times (calling `.Count()` and `.Element(i)` would clone the iterator, which meant constantly reiterating the underlying file stream), and keeping it the iterator in scope kept the file handle open.  This caused repeated file saves in VS to be unable to execute (because the file was locked), so VS would pop up a Save As dialog.
Iterating the lines once and then realizing the result into an array allows us to more efficiently compute the results using the string array rather than relying of repetitive file IO and keeping the file handle open.
Resolves #137
Also reported internally as https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1576158
> Read lines from file once when assigning lines to error items

- azure-pipelines/build.yml
- nuget.config
- test/LibraryManager.IntegrationTest/Microsoft.Web.LibraryManager.IntegrationTest.csproj
Summary of the changes:
- Sets nuget package source mappings
- Removes duplicate PackageReference in integration test project.
- Change to use NugetAuthenticate and dotnet restore instead of DotNetCoreCLI@2 task (the DotNetCoreCLI task breaks package source mappings)
> Fix warnings related to NuGet packages

- Directory.Packages.props
- build.cmd
- src/LibraryManager.Vsix/Commands/CleanCommand.cs
- src/LibraryManager.Vsix/Commands/InstallLibraryCommand.cs
- src/LibraryManager.Vsix/Commands/ManageLibrariesCommand.cs
- src/LibraryManager.Vsix/Commands/RestoreCommand.cs
- src/LibraryManager.Vsix/Commands/RestoreOnBuildCommand.cs
- src/LibraryManager.Vsix/Commands/RestoreSolutionCommand.cs
- src/LibraryManager.Vsix/Contracts/Logger.cs
- src/LibraryManager.Vsix/Json/Completion/CompletionController.cs
- src/LibraryManager.Vsix/Json/Completion/FilesCompletionProvider.cs
- src/LibraryManager.Vsix/Json/JsonHelpers.cs
- src/LibraryManager.Vsix/Json/SuggestedActions/UninstallSuggestedActions.cs
- src/LibraryManager.Vsix/Microsoft.Web.LibraryManager.Vsix.csproj
- src/LibraryManager.Vsix/UI/InstallDialog.xaml.cs
- src/LibraryManager.Vsix/UI/Models/InstallDialogViewModel.cs
- test/LibraryManager.IntegrationTest/Microsoft.Web.LibraryManager.IntegrationTest.csproj
- Updated to latest (17.7 GA) packages from VS
- Addressed some warnings, old and new
- VSTHRD analyzer complaining about unawaited tasks => explicitly discard to indicate fire-and-forget
- OutputWindowPane.OutputString is deprecated => switch to OutputWindowTextWriter, which allows free-threaded writes to an output pane
- Couple integration tests were failing by calling removed APIs => updated to latest (17.7) and tests now pass
- Pinned a few package versions to resolve MSB3277 warnings
- VS JSON parser's ArrayElementNode.Elements marked deprecated => move to ElementNodes.
> Update VS references

- src/LibraryManager.Vsix/Constants.cs
- src/LibraryManager.Vsix/Contracts/HostInteraction.cs
- src/LibraryManager.Vsix/Shared/VsHelpers.cs
We can share behavior across all CPS projects for handling files additions/removals.  CPS is much more efficient for bulk edits - they work from the file system automatically, so we don't have to do batched edits on the UI thread in VS. This is something we should take advantage of for as many project types as possible, not limited to DotNetCoreWeb.
Resolves #710
> Generalize project system interactions to CPS

- src/LibraryManager/Configuration/Settings.cs
- test/LibraryManager.Test/Configuration/SettingsTest.cs
Per #719, this can cause file lock issues with multiple concurrent processes executing (for example, parallel MSBuild nodes in a solution).  Retrospectively, it doesn't provide anything useful either.  It's faster to just create the defaults in memory than to get file IO involved.
Resolves #719
> Don't write default config file during init

- global.json
This is needed as updating VS versions often push new feature versions of the SDK (such as 8.0.200 -> 8.0.300-preview, removing 8.0.200) which breaks building locally.
> Set SDK rollforward to LatestFeature

- src/LibraryManager.Contracts/ExitCode.cs
- src/LibraryManager/Manifest.cs
- src/libman/Commands/RestoreCommand.cs
- src/libman/ExitCode.cs
- src/libman/ManifestRestorer.cs
- src/libman/Program.cs
- test/libman.Test/LibmanRestoreTest.cs
Summary of the changes
- Used return value from Microsoft.Extensions.CommandLineUtils.Execute() to propagate exit code, was hardcoded to 0
- Eliminated unclear use of IEnumerable variables with multiple enumerations when evaluating 'restore' results
Resolves #682
> #682 Add non-zero exit code on general exception and on error in Restore command

- src/LibraryManager.Contracts/FileHelpers.cs
Opening the source file without providing `FileMode` will default to `FileMode.ReadWrite`. This lead to sporadic built errors which disappeared after explicitly setting `FileMode` to `FileAccess.Read`.
> Open source file in FileMode Open

- Directory.Build.props
- src/LibraryManager.Vsix/Microsoft.Web.LibraryManager.Vsix.csproj
Many language features in recent .NET releases work fine on .NET Framework, but by default the compiler version used is based on the target framework during build.  This means that in a multitargeted project, code for .NET Framework will use a different compiler version than code for .NET, which either prevents us from using newer features, or splits the codebase.
By using so targeting the latest version of C# everywhere, it allows us to leverage those new features regardless of framework.  For any new features that have runtime requirements (i.e. are not compatible with .NET Framework), the compiler will issue an error anyway.
> Use LangVersion=latest everywhere

- src/libman/Commands/UpdateCommand.cs
- src/libman/Resources/Text.Designer.cs
- src/libman/Resources/Text.resx
All the other command parameters are consistent about following the GNU convention of using -- for long names and - for short (single-letter) names.  This one was just inconsistent.
This may be considered a breaking change, so it is best to align with the 3.0 change if possible.
> Change -pre to --pre for CLI update command

- src/LibraryManager.Build/RestoreTask.cs
With this change, the begin and end messages are no longer shown when the verbosity is minimal.  This aligns with normal output - only the project level status is shown:
```
C:\temp\project> dotnet build -v:m
MSBuild version 17.9.4+90725d08d for .NET
Determining projects to restore...
All projects are up-to-date for restore.
project -> C:\temp\project\bin\Debug\net8.0\project.dll
Build succeeded.
0 Warning(s)
0 Error(s)
```
When verbosity is increased to Normal, we see the following output for the libman restore:
```
C:\temp\project> dotnet build -v:n
...
1:7>Project "C:\temp\project\project.csproj" on node 1 (default targets).
1>LibraryManagerRestore:
Restore operation started
Restoring library jquery@3.2.1...
lib/jquery/core.js written to destination
lib/jquery/jquery.js written to …
```
> Lower MSBuild output to Normal verbosity

- LibraryManager.sln
- src/LibraryManager.Contracts/OperationResult.cs
- src/LibraryManager.Contracts/Properties/AssemblyInfo.cs
- src/LibraryManager/LibraryOperationResult.cs
- test/LibraryManager.Contracts.Test/Microsoft.Web.LibraryManager.Contracts.Test.csproj
- test/LibraryManager.Contracts.Test/OperationResultTests.cs
This type is a clone of LibraryOperationResult, but made generic.  LibraryOperationResult is similar to an Option or Maybe type, with specific metadata - whether the operation was cancelled, had errors, or was already up-to-date (all very appropriate for LibMan scenarios).  It's a useful type but limited to ILibraryInstallationState.  Introducing a generic allows the same semantics, but with any result type.  (We could deprecate LibraryOperationResult in the future, but I wanted to keep this PR as minimal as possible.)
There is one semantic difference between OperationResult and LibraryOperationResult: in the new type, a null result is considered unsuccessful, even if there are no errors provided.  That was the implied usage in LOR, but not explicit; the new type makes this explicit.
I …
> Introduce OperationResult type

- src/LibraryManager.Vsix/UI/Controls/PackageContentsTreeView.xaml.cs
If the "Files" node is partially checked, the user using spacebar will find nothing happens on spacebar because packageItem.IsChecked is null, so !packageItem.IsChecked is also null. Adjust spacebar behavior to match mouseclick behavior
> Spacebar on the "Files" node should toggle state

- src/libman/Commands/UpdateCommand.cs
- src/libman/Resources/Text.Designer.cs
- src/libman/Resources/Text.resx
This flag will cause the command to print a message indicating what changes would be made, but not commit any changes to the file system. It's useful to plan in advance before making changes.
Resolves #723
> Add a --whatif option to CLI update command

- azure-pipelines/build.yml
Removes the use of OneLocBuildPat for accessing OneLoc depencencies. Changed the package source for the OneLoc dependencies to a variable that is set on the internal pipeline to a feed with the dependencies as an upstream.
> Remove OneLocBuildPat

- src/LibraryManager.Build/Microsoft.Web.LibraryManager.Build.csproj
- src/LibraryManager/Microsoft.Web.LibraryManager.csproj
- src/LibraryManager/Minimatch/Minimatcher.cs
- src/libman/libman.csproj
This library provides the glob expansion logic used in LibMan.  However, the package published to nuget.org is based on an ancient .NET Standard prerelease version, which causes lots of cascading package version conflicts sometimes.  We've suppressed those in some cases, but it still can arise when consuming new packages.
This change takes a direct copy of the source code for this type. Copyright attributions is placed in the file, as is a link back to the source.  The original was licensed under the MIT license.
These sources haven't changed in 11 years, it's unlikely they'll change again (although now we could if we need to).
> Copy minimatch sources and remove package dependency

- Directory.Packages.props
- src/LibraryManager.Build/Microsoft.Web.LibraryManager.Build.csproj
- src/LibraryManager.Vsix/Microsoft.Web.LibraryManager.Vsix.csproj
https://github.com/aspnet/LibraryManager/pull/747 removed some references to Minimatch.dll but left a few behind.
Remove those latent references.
> Followup: Fully remove references

- src/LibraryManager.Build/Microsoft.Web.LibraryManager.Build.csproj
- src/LibraryManager.Contracts/Microsoft.Web.LibraryManager.Contracts.csproj
- src/LibraryManager/Microsoft.Web.LibraryManager.csproj
Netstandard gives compatibility benefits for libraries to be used against netfx or netcore frameworks.  However, for libman, all of our projects that run on netcore already target that framework directly.
This change modifies the existing multitargeted projects to target netcore directly instead of netstandard.  This will allow future changes to use conditional compilation to leverage newer APIs in netcore that do not exist in the netstandard API surface.
The only breaking change here is that the Build project now uses .NET 8 for the build task.  This means consumers of that package who are not using .NET Framework will need to have a compatible version of the SDK; however, this aligns with the prior change in the CLI tool to require .NET 8 as well.
> Drop netstandard for $(NetCoreTFM)

- src/LibraryManager/Cache/WebRequestHandler.cs
- src/LibraryManager/Configuration/Constants.cs
Per #711 (and #699 before it), some users need to force TLS 1.2 for libman to work.
This change adds a new user setting, "forcetls12", which will set libman to use TLS1.2 for any HttpClient it creates.
I verified via WireShark that the traffic to services (cdnjs, etc) that libman calls to switched from 1.3 (my system default) to 1.2 when this setting was in place, and returned to 1.3 by unsetting it.  I could also see that other connections from within VS were still using TLS1.3 so we didn't affect other components on accident.
Resolves #711
> Add setting to force TLS 1.2

- src/LibraryManager/ManifestConstants.cs
- src/LibraryManager/Providers/BaseProvider.cs
- src/LibraryManager/Providers/Cdnjs/CdnjsCatalog.cs
- src/LibraryManager/Providers/Unpkg/UnpkgCatalog.cs
- src/LibraryManager/Providers/jsDelivr/JsDelivrCatalog.cs
- test/LibraryManager.Test/Providers/Cdnjs/CdnjsCatalogTest.cs
Currently, unpkg and jsdelivr support using 'latest' as a version.  When files are requested by libman, they redirect (HTTP302) to the URL for the current latest files.  We put those files into the cache like any other version (in a folder name 'latest') and all is well.
However, when a new version is released, libman continues to use the now-stale downloaded assets from the cache.  There isn't a signal to realize when to purge the latest version from the cache.
This change instead simply turns 'latest' into the latest version we determine from the provider.  There is a small risk that we are out of sync with the CDN: for example, since we get the version data from NPM, it might not match the version that e.g. jsdelivr redirects to.  But this should be extremely rare.
Doing it this way …
> Rework support for @latest version

- Directory.Build.props
- Directory.Packages.props
- LibraryManager.sln
- src/LibraryManager.Vsix/Microsoft.Web.LibraryManager.Vsix.csproj
- test/LibraryManager.IntegrationTest/LibmanCompletionTests.cs
- test/LibraryManager.Mocks/Microsoft.Web.LibraryManager.Mocks.csproj
Update a number of packages to be more modern
Stop shipping binaries to run in VisualStudio that VisualStudio already ships (With binding redirects/etc.)
Update the SLN file so that the Vsix project is the default startup project.
> Update package references

- src/LibraryManager.Contracts/FileHelpers.cs
- test/LibraryManager.Test/FileHelpersTest.cs
The logic had a flaw that it didn't verify the directory separator after the directory portion.  NormalizePath strips trailing slashes, so there will never be one.  However, for IsUnderRootDirectory, there must be a separator in the path.
> Fix bug in FileHelpers.IsUnderRootDirectory for separator

- src/LibraryManager.Contracts/FileMapping.cs
- src/LibraryManager.Contracts/ILibraryInstallationState.cs
- src/LibraryManager/Json/FileMapping.cs
- src/LibraryManager/Json/LibraryInstallationStateOnDisk.cs
- src/LibraryManager/Json/LibraryStateToFileConverter.cs
- src/LibraryManager/LibraryInstallationState.cs
- src/LibraryManager/Manifest.cs
- src/LibraryManager/ManifestConstants.cs
- src/LibraryManager/Providers/BaseProvider.cs
- src/schema/libman.json
- test/LibraryManager.Mocks/LibraryInstallationState.cs
- test/LibraryManager.Test/Providers/BaseProviderTest.cs
- test/libman.Test/BaseCommandTests.cs
- test/libman.Test/LibmanInitTests.cs
- test/libman.Test/LibmanInstallTest.cs
Summary of the changes:
- Adds support for parsing fileMappings and calculating the goal state from them.
- Adds support for fileMappings to the schema.  Includes a schema validation error if the schema uses fileMappings but doesn't have a sufficiently high version set.
- Enables manifest version "3.0" and sets that as the default for newly created manifests.
This implements #738.  There will be an additional PR to make the JSON completion in the editor work for fileMappings.
> Implement support for "fileMappings"

- src/LibraryManager.Build/Microsoft.Web.LibraryManager.Build.csproj
- src/LibraryManager.Build/Microsoft.Web.LibraryManager.Build.targets
Fixes two issues in the recent changes to the targets file in the Build package:
- The path to the build task assembly was incorrectly updated since we now build the project for net8.0 and net481.  Also, it was updated to use an MSBuild variable that exists in this repo, but the targets file runs in the context of the consumer (which wouldn't have it defined).  So the path was returned to a hard-coded value.  This will need to be maintained as target frameworks get updated (or we need a better way to generate the targets file).
- The Build package was passing the dependency to System.Runtime.Loader transitively.  This was causing warnings with .NET 9's stricter security advisory due to the runtime dependencies (System.Private.Uri specifically).  This should not be a transitive dependency …
> Fix build targets

- azure-pipelines/build.yml
Add service connection conditionally
Update "Install .NET SDK" action to use the contents of global.json to determine the version of the SDK to install
> Add service connection for NugetAuthenticate

- src/LibraryManager.Contracts/FileHelpers.cs
- src/LibraryManager/Providers/BaseProvider.cs
This can cause issues if we assume a case-insensitive environment, but a user has a case-sensitive tool.
Instead, when trying to find duplicate paths, we'll let a StringComparer do the work to determine if the paths are the same.
Resolves #779
> Change file normalization to not lowercase all file names

- src/LibraryManager.Build/Microsoft.Web.LibraryManager.Build.csproj
The Microsoft.Web.LibraryManager.Build package contains all of its dependencies.  This project reference was also getting added as a package dependency, which is redundant.
> Prevent dependency on Contracts package

- src/LibraryManager.Build/RestoreTask.cs
During the switch to using LibraryInstallationGoalState, we changed the behavior of taking a LibraryInstallationState and "updating" it to reflect the published files (this transform would expand the Files from globs to a full list).  That's now done by LibraryInstallationGoalState, which also takes into account the FileMappings, and produces a set of the destination files.
This was somehow overlooked in this build task, which caused it to throw a NRE when it was looking at the LibraryInstallationState (now that it wasn't being "updated", the Files were null in many cases).
This fix re-computes each successful LibraryInstallationState into the LibraryInstallationGoalState, which contains the list of files that were installed by that library.
This isn't the ideal fix.  I think it would be …
> Fix RestoreTask tallying of written files

- LibraryManager.sln
- test/LibraryManager.Build.IntegrationTest/BuildTestBase.cs
- test/LibraryManager.Build.IntegrationTest/Microsoft.Web.LibraryManager.Build.IntegrationTest.csproj
- test/LibraryManager.Build.IntegrationTest/RestoreTests.cs
- test/LibraryManager.Build.IntegrationTest/TestSolution/Directory.Build.props
- test/LibraryManager.Build.IntegrationTest/TestSolution/Directory.Build.targets
- test/LibraryManager.Build.IntegrationTest/TestSolution/Directory.Packages.props
- test/LibraryManager.Build.IntegrationTest/TestSolution/Libman.Build.TestApp.sln
- test/LibraryManager.Build.IntegrationTest/TestSolution/Libman.Build.TestApp/Libman.Build.TestApp.csproj
- test/LibraryManager.Build.IntegrationTest/TestSolution/Libman.Build.TestApp/Program.cs
- test/LibraryManager.Build.IntegrationTest/TestSolution/Libman.Build.TestApp/Properties/launchSettings.json
- test/LibraryManager.Build.IntegrationTest/TestSolution/Libman.Build.TestApp/appsettings.Development.json
- test/LibraryManager.Build.IntegrationTest/TestSolution/Libman.Build.TestApp/appsettings.json
- test/LibraryManager.Build.IntegrationTest/TestSolution/nuget.config
- test/libman.IntegrationTest/CliBaseTest.cs
- test/libman.IntegrationTest/InstallTests.cs
- test/libman.IntegrationTest/RestoreTests.cs
- test/libman.IntegrationTest/libman.IntegrationTest.csproj
Each new integration test project has steps to set up using the package from the current build.  This will allow more consistent testing in addition to the Visual Studio integration tests.
Currently each project just has some basic tests to get started.  We can add more scenarios later, this PR is to introduce the core infrastructure with some basic starters.
> Integration tests for CLI and Build task
