- src/LibraryManager.Vsix/Contracts/HostInteraction.cs
- src/LibraryManager.Vsix/Json/FileIdentifier.cs
- src/LibraryManager.Vsix/Json/TextviewCreationListener.cs
- src/LibraryManager.Vsix/Microsoft.Web.LibraryManager.Vsix.csproj
- Using a Tuple<string, string> for <filepath, version> instead of a single path with the version appended at the end of path.
> Addressing code review feedback

- LibraryManager.sln
- appveyor.yml
- src/LibraryManager.Build/Microsoft.Web.LibraryManager.Build.csproj
- src/LibraryManager.Contracts/Microsoft.Web.LibraryManager.Contracts.csproj
- src/LibraryManager.Vsix/Microsoft.Web.LibraryManager.Vsix.csproj
- src/LibraryManager.Vsix/Properties/AssemblyInfo.cs
- src/LibraryManager.Vsix/source.extension.cs
- src/LibraryManager.Vsix/source.extension.vsixmanifest
- src/LibraryManager/Microsoft.Web.LibraryManager.csproj
- test/LibraryManager.Mocks/Microsoft.Web.LibraryManager.Mocks.csproj
- test/LibraryManager.Test/Microsoft.Web.LibraryManager.Test.csproj
- test/Microsoft.Web.LibraryManager.Build.Test/Microsoft.Web.LibraryManager.Build.Test.csproj
- version.json
This adds Nerdbank.GitVersioning to all projects.  This package provides auto-incrementing revisions to the binaries and nupkgs, and the commit hash into the AssemblyInformationalVersion.  It also updates the version in the vsixmanifest file.
> Generate auto-incrementing versions using GitVersioning

- src/LibraryManager.Contracts/Resources/Text.Designer.cs
- src/LibraryManager.Contracts/Resources/Text.resx
Fixing bug 584048: LibMan: update error messages to reference new schema elements
> Fixing error messages to reflect new json schema elements

- src/LibraryManager.Build/RestoreTask.cs
- src/LibraryManager.Contracts/PredefinedErrors.cs
- src/LibraryManager.Vsix/ErrorList/ErrorList.cs
- src/LibraryManager.Vsix/Json/TextviewCreationListener.cs
- src/LibraryManager.Vsix/Shared/LibraryHelpers.cs
- src/LibraryManager/LibraryInstallationResult.cs
- src/LibraryManager/Manifest.cs
- test/LibraryManager.Test/ManifestTest.cs
- test/Microsoft.Web.LibraryManager.Build.Test/RestoreTaskTest.cs
> Version validation and error handling.

- src/LibraryManager/Resources/Text.Designer.cs
- src/LibraryManager/Resources/Text.resx
Add hint text for unpkg provider
> Add hint text for unpkg provider

- appveyor.yml
- src/LibraryManager.Build/Contracts/Dependencies.cs
- src/LibraryManager.Build/Microsoft.Web.LibraryManager.Build.csproj
- src/LibraryManager.Build/Microsoft.Web.LibraryManager.Build.props
- src/LibraryManager.Build/Microsoft.Web.LibraryManager.Build.targets
- src/LibraryManager.Contracts/Microsoft.Web.LibraryManager.Contracts.csproj
- src/LibraryManager.Vsix/Microsoft.Web.LibraryManager.Vsix.csproj
- src/LibraryManager/Microsoft.Web.LibraryManager.csproj
- test/LibraryManager.Mocks/Microsoft.Web.LibraryManager.Mocks.csproj
- test/LibraryManager.Test/Microsoft.Web.LibraryManager.Test.csproj
- test/Microsoft.Web.LibraryManager.Build.Test/Microsoft.Web.LibraryManager.Build.Test.csproj
Retarget to netstandard 2.0, netcoreapp2.0;net461
> Retarget to etstandard 2.0, netcoreapp2.1;net461

- .editorconfig
Making formatting rules a little more stringent so that we don't have to call these out in PRs.
> Formatting rules

- src/LibraryManager.Vsix/UI/Controls/Library.xaml.cs
- src/LibraryManager.Vsix/UI/Controls/TargetLocation.xaml.cs
- src/LibraryManager.Vsix/UI/InstallDialog.xaml.cs
The changes fix below two issues:
- Close popup on commit
- Refine search for destination folder to show most relevant results first
> Fix popup issue and refresh search

- src/LibraryManager.Vsix/UI/InstallDialog.xaml
- src/LibraryManager.Vsix/UI/InstallDialog.xaml.cs
- src/LibraryManager.Vsix/UI/Models/InstallDialogViewModel.cs
Recursively check if files are selected to makes sure if we are good to install.
> Recursively check if files are selected

- src/LibraryManager.Vsix/UI/InstallDialog.xaml
- src/LibraryManager.Vsix/UI/InstallDialog.xaml.cs
- src/LibraryManager.Vsix/UI/Models/InstallDialogViewModel.cs
Recursively check if files are selected
> Fix unpkg file selection issue

- src/LibraryManager/Providers/Cdnjs/CdnjsCatalog.cs
- test/LibraryManager.Test/Providers/Cdnjs/CdnjsCatalogTest.cs
This is to resolve https://github.com/aspnet/LibraryManager/issues/120
> Remove bootstrap special case alias

- src/LibraryManager/Providers/Unpkg/NpmPackageSearch.cs
This is to resolve bug https://github.com/aspnet/LibraryManager/issues/150
> make colon works for library id intellisense

- src/LibraryManager.Vsix/Contracts/Logger.cs
Fixing internally logged bug 599568 "LibMan hung when closing the project with an unsaved libman.json file"
The issue here was that we were accessing output window on the background thread. In the dump file attached to the bug you can see that we were clearing output window on the UI thread (on solution close) while library restore command was trying to log messages to the output window on a background thread.
IVsOutputWindowPane (along with most other IVsXXX services) should be accessed on the main thread only. It's not thread safe. This fix ensures that all VS services used by the Logger class are accessed on the main thread only.
> Fixing output window hang

- test/LibraryManager.IntegrationTest/FileSaveRestoreTests.cs
- test/LibraryManager.IntegrationTest/Helpers/CompletionHelper.cs
- test/LibraryManager.IntegrationTest/Helpers/FileIOHelper.cs
- test/LibraryManager.IntegrationTest/Helpers/HelperWrapper.cs
- test/LibraryManager.IntegrationTest/LibmanCompletionTests.cs
- test/LibraryManager.IntegrationTest/VisualStudioLibmanHostTests.cs
The goal is to create a simpler API for discovering test utilities through the Helpers property, instead of having to reference static utilities.
> Refactor helpers into classes under a consolidated hierarchy

- src/LibraryManager.Vsix/Contracts/Logger.cs
I left a variable unset by mistake causing wrong error messages when restore partially works.
> Fixing error message issue

- src/LibraryManager.Vsix/UI/InstallDialog.xaml.cs
- src/LibraryManager.Vsix/UI/Models/InstallDialogViewModel.cs
Change to not include all files when include all files option is checked in the UI.
> Do not list all files when include all files option is checked

- src/LibraryManager.Vsix/Commands/CommandTable/VSCommandTable.en.vsct
- src/LibraryManager.Vsix/Resources/Text.Designer.cs
- src/LibraryManager.Vsix/Resources/Text.resx
> Added accelerator keys for menu items.

- src/LibraryManager.Build/RestoreTask.cs
> Making RestoreTask public

- src/LibraryManager.Vsix/Commands/RestoreOnBuildCommand.cs
Package is enabled for Web Projects only, The existing test in incorrect and not necessary.
> Enabling "restore on build" command for non Core projects.

- src/LibraryManager.Vsix/Resources/Text.Designer.cs
- src/LibraryManager.Vsix/Resources/Text.resx
- src/LibraryManager.Vsix/UI/InstallDialog.xaml
Localize install and cancel buttons
> Localize install and cancel buttons

- src/LibraryManager.Vsix/Json/Completion/CompletionController.cs
- test/LibraryManager.IntegrationTest/LibmanCompletionTests.cs
This can resolve https://github.com/aspnet/LibraryManager/issues/172
> delete will intrigue completion as to be consistent to Json Editors.

- src/LibraryManager.Vsix/Contracts/Logger.cs
- src/LibraryManager/Logging/LogMessageGenerator.cs
- src/libman/Commands/BaseCommand.cs
- src/libman/Commands/CleanCommand.cs
- src/libman/Commands/RestoreCommand.cs
- src/libman/ManifestRestorer.cs
- src/libman/Resources.Designer.cs
- src/libman/Resources.resx
> Adds summary output line for CLI clean command

- src/LibraryManager.Build/Contracts/HostInteraction.cs
- src/LibraryManager.Contracts/FileHelpers.cs
- src/LibraryManager.Contracts/Properties/AssemblyInfo.cs
- src/LibraryManager.Vsix/Contracts/HostInteraction.cs
- src/libman/Contracts/HostInteraction.cs
- test/LibraryManager.Test/ErrorTest.cs
- test/LibraryManager.Test/FileHelpersTest.cs
- test/LibraryManager.Test/PathEqualityComparerTest.cs
- test/libman.Test/LibmanCleanTest.cs
This is to resolve https://github.com/aspnet/LibraryManager/issues/119
> delete empty folders after clean operation.

- src/LibraryManager.Vsix/Commands/InstallLibraryCommand.cs
Includes changes to validate the manifest before invoking add client side libraries dialog.
> Check for syntax errors before invoking add client side libraries dialog

- src/LibraryManager.Vsix/UI/InstallDialog.xaml.cs
This is to resolve https://github.com/aspnet/LibraryManager/issues/307
> check for start of the path, trim if start with "/" or "\" when setting the destination folder.

- src/LibraryManager.Vsix/Commands/InstallLibraryCommand.cs
- src/LibraryManager.Vsix/UI/InstallDialog.xaml.cs
- src/LibraryManager.Vsix/UI/Models/InstallDialogViewModel.cs
This is to resolve first part of https://github.com/aspnet/LibraryManager/issues/309
> Make adding client-library work for .NET project

- build/PackageVersions.targets
Merging changes to master from `rel/15.8`
> Downgrade System.ValueTuple to match verison in VisualStudio

- src/LibraryManager.Vsix/UI/Controls/Library.xaml
- src/LibraryManager.Vsix/UI/Controls/PackageContentsTreeView.xaml
- src/LibraryManager.Vsix/UI/Controls/TargetLocation.xaml
Fix accessibility issues(flagged by keros tool) related to name property of the controls.
> Fix accessibility bugs related to name property

- src/LibraryManager.Vsix/Microsoft.Web.LibraryManager.Vsix.csproj
- src/LibraryManager.Vsix/UI/Controls/Library.xaml
- src/LibraryManager.Vsix/UI/Controls/Library.xaml.cs
- src/LibraryManager.Vsix/UI/Controls/LibraryAutomationPeer.cs
- src/LibraryManager.Vsix/UI/Controls/PackageContentsTreeView.xaml
- src/LibraryManager.Vsix/UI/Controls/PackageContentsTreeView.xaml.cs
- src/LibraryManager.Vsix/UI/Controls/PackageContentsTreeViewAutomationPeer.cs
- src/LibraryManager.Vsix/UI/Controls/TargetLocation.xaml
- src/LibraryManager.Vsix/UI/Controls/TargetLocation.xaml.cs
- src/LibraryManager.Vsix/UI/Controls/TargetLocationAutomationPeer.cs
- src/LibraryManager.Vsix/UI/InstallDialog.xaml
Merge changes from rel/15.9 to master
> Merge changes from rel/15.9 to master

- src/LibraryManager.Vsix/source.extension.vsixmanifest
Update versions in vsix manifest
How was it tested?
- Unit tests
- Integration tests
> Update versions in vsix manifest

- src/LibraryManager/Providers/Cdnjs/CdnjsCatalog.cs
> Get the latest version of a library in CDNJS from Version property

- src/LibraryManager.Vsix/Resources/Text.Designer.cs
- src/LibraryManager.Vsix/Resources/Text.resx
- src/LibraryManager.Vsix/UI/Controls/Library.xaml.cs
- src/LibraryManager.Vsix/UI/Controls/TargetLocation.xaml.cs
- src/LibraryManager.Vsix/UI/InstallDialog.xaml
Added access keys to UI controls
How was it tested?
- Ran all tests
> Add access keys to UI controls

- src/LibraryManager/Manifest.cs
Not sure why AppVeyor doesn't hit the issue.
> Disable assert which is preventing running unit tests locally

- src/LibraryManager.Vsix/UI/InstallDialog.xaml
Make help text icon accessible and fix tab order of items in dockpanel.
> Make help text icon accessible

- src/LibraryManager.Vsix/Json/SuggestedActions/UpdateSuggestedActionSet.cs
- src/LibraryManager.Vsix/Resources/Text.Designer.cs
- src/LibraryManager.Vsix/Resources/Text.resx
This addresses #348 after the subsequent loc handback.
> Refactor hardcoded strings into resources for Update lightbulb action

- src/LibraryManager.Vsix/Microsoft.Web.LibraryManager.Vsix.csproj
- src/LibraryManager.Vsix/UI/Controls/Library.xaml
- src/LibraryManager.Vsix/UI/Controls/Library.xaml.cs
- src/LibraryManager.Vsix/UI/Controls/TargetLocation.xaml
- src/LibraryManager.Vsix/UI/Extensions/RemoveCharacterExtension.cs
- src/LibraryManager.Vsix/UI/InstallDialog.xaml
This pr includes changes to make sure narrator reads the watermark text in library search box when it's empty.
> Changes to make sure narrator reads watermark text in library search box

- src/LibraryManager.Vsix/UI/InstallDialog.xaml.cs
Fixes internally tracked accessibility issue 893985.
> Ensures focus is in the Library Search text box on Install dialog load

- src/LibraryManager/Providers/Unpkg/NpmPackageSearch.cs
Switching search to use registry database and API since skimdb was retired.
> Fixing npm search

- build/PackageVersions.targets
- src/LibraryManager.Vsix/Commands/CleanCommand.cs
- src/LibraryManager.Vsix/Commands/InstallLibraryCommand.cs
- src/LibraryManager.Vsix/Commands/ManageLibrariesCommand.cs
- src/LibraryManager.Vsix/Commands/RestoreCommand.cs
- src/LibraryManager.Vsix/Commands/RestoreOnBuildCommand.cs
- src/LibraryManager.Vsix/Commands/RestoreSolutionCommand.cs
- src/LibraryManager.Vsix/ErrorList/TableDataSource.cs
- src/LibraryManager.Vsix/Json/SuggestedActions/UpdateSuggestedActionSet.cs
- src/LibraryManager.Vsix/LibraryManagerPackage.cs
- src/LibraryManager.Vsix/Microsoft.Web.LibraryManager.Vsix.csproj
- src/LibraryManager.Vsix/UI/InstallDialog.xaml
- src/LibraryManager.Vsix/UI/InstallDialog.xaml.cs
- src/LibraryManager.Vsix/UI/Models/InstallDialogViewModel.cs
3 types of issues were found by analyzers:
- use of async void methods
- not checking for null on GetService calls
- awaiting foreign task
This PR supercedes #261.
> Enable VSSDK analyzers and fix analyzer issues

- build.cmd
- src/LibraryManager/CacheService/CacheFileMetadata.cs
- src/LibraryManager/Providers/BaseProvider.cs
> Address engineering debt carried over from #534

- src/LibraryManager/LibraryNaming/VersionedLibraryNamingScheme.cs
> Contributing: fix a typo

- src/LibraryManager.Vsix/UI/IInstallDialog.cs
- src/LibraryManager.Vsix/UI/InstallDialog.xaml.cs
- src/LibraryManager/Providers/Unpkg/NpmPackageInfo.cs
- src/LibraryManager/Providers/Unpkg/UnpkgCatalog.cs
- src/LibraryManager/Providers/jsDelivr/JsDelivrCatalog.cs
- test/LibraryManager.IntegrationTest/InstallDialogTests.cs
- test/LibraryManager.IntegrationTest/LibmanCompletionTests.cs
- test/LibraryManager.IntegrationTest/Services/InstallDialogTestExtension.cs
> Add support for @latest version in jsdelivr and unpkg

- src/LibraryManager/MultilingualResources/Microsoft.Web.LibraryManager.cs.xlf
- src/LibraryManager/MultilingualResources/Microsoft.Web.LibraryManager.de.xlf
- src/LibraryManager/MultilingualResources/Microsoft.Web.LibraryManager.es.xlf
- src/LibraryManager/MultilingualResources/Microsoft.Web.LibraryManager.fr.xlf
- src/LibraryManager/MultilingualResources/Microsoft.Web.LibraryManager.it.xlf
- src/LibraryManager/MultilingualResources/Microsoft.Web.LibraryManager.ja.xlf
- src/LibraryManager/MultilingualResources/Microsoft.Web.LibraryManager.ko.xlf
- src/LibraryManager/MultilingualResources/Microsoft.Web.LibraryManager.pl.xlf
- src/LibraryManager/MultilingualResources/Microsoft.Web.LibraryManager.pt-BR.xlf
- src/LibraryManager/MultilingualResources/Microsoft.Web.LibraryManager.ru.xlf
- src/LibraryManager/MultilingualResources/Microsoft.Web.LibraryManager.tr.xlf
- src/LibraryManager/MultilingualResources/Microsoft.Web.LibraryManager.zh-Hans.xlf
- src/LibraryManager/MultilingualResources/Microsoft.Web.LibraryManager.zh-Hant.xlf
- src/libman/MultilingualResources/libman.fr.xlf
- src/libman/MultilingualResources/libman.pt-BR.xlf
- src/libman/MultilingualResources/libman.tr.xlf
- src/libman/MultilingualResources/libman.zh-Hant.xlf
43fbbc90965a7e11b69a191706551e16a0630494 from LibraryManager.Loc repo
> Loc handback

- src/libman/Commands/CacheListCommand.cs
- Add list of special file names to suppress.
- Skip foreach iteration if special file found.
Addresses #125
> Suppress metadata files in cache list.

- src/LibraryManager/Configuration/Constants.cs
- src/LibraryManager/Configuration/ProxySettings.cs
- src/LibraryManager/Configuration/Settings.cs
- test/LibraryManager.Test/Configuration/SettingsTest.cs
> Read settings from environment variables

- test/LibraryManager.Test/Providers/Unpkg/NpmPackageSearchTest.cs
Yes, yes, someone did create a package with poiuytrewq in the name.
> Add more entropy to fake library name

- test/LibraryManager.Test/Providers/Cdnjs/CdnjsProviderTest.cs
- test/libman.Test/LibmanInstallTest.cs
- test/libman.Test/LibmanUpdateTest.cs
Also fixed a reliability issue in cdnjs provider tests.
> Fix tests affected by jQuery 3.5.0 release

- azure-pipelines/build.yml
We can turn on auto-complete after we've built better trust in the new system
> Don't auto-complete localization handback PRs

- src/LibraryManager.Vsix/Resources/loc/cs/Resources/Text.resx.lcl
- src/LibraryManager.Vsix/Resources/loc/cs/source.extension.resx.lcl
- src/LibraryManager.Vsix/Resources/loc/ko/Resources/Text.resx.lcl
- src/LibraryManager.Vsix/Resources/loc/zh-Hans/Resources/Text.resx.lcl
- src/LibraryManager/Resources/loc/cs/Resources/Text.resx.lcl
- src/LibraryManager/Resources/loc/ko/Resources/Text.resx.lcl
- src/LibraryManager/Resources/loc/zh-Hans/Resources/Text.resx.lcl
- src/libman/Resources/loc/cs/Resources/Text.resx.lcl
- src/libman/Resources/loc/ko/Resources/Text.resx.lcl
- src/libman/Resources/loc/zh-Hans/Resources/Text.resx.lcl
LEGO: Pull request from lego/hb_bffd58c1-56d2-478d-96be-20bc98f118aa_20210226174730443 to main with localized lcls
> LEGO: Pull request from lego/hb_bffd58c1-56d2-478d-96be-20bc98f118aa_20210226174730443 to main

- src/LibraryManager.Vsix/Resources/loc/de/Resources/Text.resx.lcl
- src/LibraryManager.Vsix/Resources/loc/fr/Resources/Text.resx.lcl
- src/LibraryManager.Vsix/Resources/loc/fr/source.extension.resx.lcl
- src/LibraryManager.Vsix/Resources/loc/pl/Resources/Text.resx.lcl
- src/LibraryManager.Vsix/Resources/loc/pl/source.extension.resx.lcl
- src/LibraryManager.Vsix/Resources/loc/pt-BR/Resources/Text.resx.lcl
- src/LibraryManager.Vsix/Resources/loc/pt-BR/source.extension.resx.lcl
- src/LibraryManager.Vsix/Resources/loc/ru/Resources/Text.resx.lcl
- src/LibraryManager.Vsix/Resources/loc/ru/source.extension.resx.lcl
- src/LibraryManager.Vsix/Resources/loc/tr/Resources/Text.resx.lcl
- src/LibraryManager.Vsix/Resources/loc/tr/source.extension.resx.lcl
- src/LibraryManager/Resources/loc/de/Resources/Text.resx.lcl
- src/LibraryManager/Resources/loc/fr/Resources/Text.resx.lcl
- src/LibraryManager/Resources/loc/pl/Resources/Text.resx.lcl
- src/LibraryManager/Resources/loc/pt-BR/Resources/Text.resx.lcl
- src/LibraryManager/Resources/loc/ru/Resources/Text.resx.lcl
- src/LibraryManager/Resources/loc/tr/Resources/Text.resx.lcl
- src/libman/Resources/loc/de/Resources/Text.resx.lcl
- src/libman/Resources/loc/fr/Resources/Text.resx.lcl
- src/libman/Resources/loc/pl/Resources/Text.resx.lcl
- src/libman/Resources/loc/pt-BR/Resources/Text.resx.lcl
- src/libman/Resources/loc/ru/Resources/Text.resx.lcl
- src/libman/Resources/loc/tr/Resources/Text.resx.lcl
LEGO: Pull request from lego/hb_bffd58c1-56d2-478d-96be-20bc98f118aa_20210227175326593 to main with localized lcls
> LEGO: Pull request from lego/hb_bffd58c1-56d2-478d-96be-20bc98f118aa_20210227175326593 to main

- src/LibraryManager.Vsix/Resources/loc/ja/Resources/Text.resx.lcl
- src/LibraryManager.Vsix/Resources/loc/ja/source.extension.resx.lcl
- src/LibraryManager/Resources/loc/ja/Resources/Text.resx.lcl
- src/libman/Resources/loc/ja/Resources/Text.resx.lcl
LEGO: Pull request from lego/hb_bffd58c1-56d2-478d-96be-20bc98f118aa_20210301174727725 to main with localized lcls
> LEGO: Pull request from lego/hb_bffd58c1-56d2-478d-96be-20bc98f118aa_20210301174727725 to main

- src/LibraryManager.Vsix/Resources/loc/es/Resources/Text.resx.lcl
- src/LibraryManager.Vsix/Resources/loc/es/source.extension.resx.lcl
- src/LibraryManager.Vsix/Resources/loc/zh-Hant/Resources/Text.resx.lcl
- src/LibraryManager.Vsix/Resources/loc/zh-Hant/source.extension.resx.lcl
- src/LibraryManager/Resources/loc/es/Resources/Text.resx.lcl
- src/LibraryManager/Resources/loc/zh-Hant/Resources/Text.resx.lcl
- src/libman/Resources/loc/es/Resources/Text.resx.lcl
- src/libman/Resources/loc/zh-Hant/Resources/Text.resx.lcl
LEGO: Pull request from lego/hb_bffd58c1-56d2-478d-96be-20bc98f118aa_20210302211019119 to main with localized lcls
> LEGO: Pull request from lego/hb_bffd58c1-56d2-478d-96be-20bc98f118aa_20210302211019119 to main

- src/LibraryManager.Vsix/Resources/loc/it/Resources/Text.resx.lcl
- src/LibraryManager.Vsix/Resources/loc/it/source.extension.resx.lcl
- src/LibraryManager/Resources/loc/it/Resources/Text.resx.lcl
- src/libman/Resources/loc/it/Resources/Text.resx.lcl
LEGO: Pull request from lego/hb_bffd58c1-56d2-478d-96be-20bc98f118aa_20210304175325458 to main with localized lcls
> LEGO: Pull request from lego/hb_bffd58c1-56d2-478d-96be-20bc98f118aa_20210304175325458 to main

- src/LibraryManager.Contracts/Resources/loc/fr/Resources/Text.resx.lcl
- src/LibraryManager.Contracts/Resources/loc/ja/Resources/Text.resx.lcl
- src/LibraryManager.Contracts/Resources/loc/ko/Resources/Text.resx.lcl
- src/LibraryManager.Contracts/Resources/loc/pt-BR/Resources/Text.resx.lcl
LEGO: Pull request from lego/hb_bffd58c1-56d2-478d-96be-20bc98f118aa_20210327000928578 to main with localized lcls
> LEGO: Pull request from lego/hb_bffd58c1-56d2-478d-96be-20bc98f118aa_20210327000928578 to main

- src/LibraryManager.Vsix/Commands/InstallLibraryCommand.cs
- src/LibraryManager.Vsix/UI/InstallDialog.xaml
- src/LibraryManager.Vsix/UI/Models/InstallDialogViewModel.cs
- test/LibraryManager.IntegrationTest/InstallDialogTests.cs
> Wizard should respect defaultProvider if specified

- src/LibraryManager.Vsix/Json/TextviewCreationListener.cs
The IDependencies includes information about the working directory for
restore.  We were using a saved instance of this, but would reset it
whenever a new TextView was opened for a libman.json file.
This would set the cached working directory to the last opened
libman.json file, and changes to any other libman.json file would then
restore in that folder.
Fixes #638
> Ensure manifest restore uses matching dependencies

- src/LibraryManager.Vsix/Resources/Text.Designer.cs
- src/LibraryManager.Vsix/Resources/Text.resx
- src/LibraryManager.Vsix/UI/Controls/TextBoxWithSearch.xaml.cs
> Show an indicator when there are no search matches

- src/LibraryManager.Vsix/Json/Completion/CompletionController.cs
> Don't retrigger completion after a completed string value

- src/libman/Commands/InitCommand.cs
- src/libman/Resources/Text.Designer.cs
- src/libman/Resources/Text.resx
- test/libman.Test/LibmanInitTests.cs
> Add a flag to silently init using the default provider

- src/LibraryManager.Vsix/Resources/Text.Designer.cs
- src/LibraryManager.Vsix/Resources/Text.resx
> Remove ambiguous usage of "Library"

- src/LibraryManager.Vsix/Resources/Text.Designer.cs
- src/LibraryManager.Vsix/Resources/Text.resx
- src/LibraryManager.Vsix/UI/InstallDialog.xaml.cs
- src/LibraryManager.Vsix/UI/Models/InstallDialogViewModel.cs
- src/LibraryManager/LibraryNaming/ILibraryNamingScheme.cs
- src/LibraryManager/LibraryNaming/LibraryIdToNameAndVersionConverter.cs
- src/LibraryManager/LibraryNaming/SimpleLibraryNamingScheme.cs
- src/LibraryManager/LibraryNaming/VersionedLibraryNamingScheme.cs
- test/LibraryManager.Test/SimpleLibraryNamingSchemeTest.cs
- test/LibraryManager.Test/VersionedLibraryNamingSchemeTest.cs
> Improve error message in wizard when installing an invalid library name

- Directory.Packages.props
This hopefully will address the SymbolCheck issues we're getting from Nuget.VisualStudio.dll during VS insertion.
> Update to latest VS dependencies

- Directory.Build.props
Adding these flags per current security guidelines
> Add HighEntropyVa & CheckForOverflowUnderflow flags

- src/LibraryManager/CacheService/WebRequestHandler.cs
- src/LibraryManager/Providers/Cdnjs/CdnjsCatalog.cs
Summary of the changes:
- Switches away from relying on "assets" including information for all library versions.
- Add user agent to the web requests.
> Port changes to adapt to Cdnjs API change

- nuget.config
> Use consolidated nuget feed

- azure-pipelines.yml
- azure-pipelines/azure-pipeline.microbuild.after.yml
- azure-pipelines/azure-pipeline.microbuild.before.yml
- azure-pipelines/build.yml
- azure-pipelines/official.yml
Convert official pipeline to1ES template
> Convert official pipeline to1ES template

- src/libman/Commands/InstallCommand.cs
> Use forward slash for CLI install suggested path

- src/LibraryManager.Contracts/PredefinedErrors.cs
- src/LibraryManager.Contracts/Resources/Text.Designer.cs
- src/LibraryManager.Contracts/Resources/Text.resx
- src/LibraryManager/LibrariesValidator.cs
- test/LibraryManager.Test/ManifestTest.cs
> Add an error when the manifest is missing a version

- azure-pipelines/official.yml
Add retention of artifacts back to the official pipeline
> Add retention of artifacts back to the official pipeline

- azure-pipelines/official.yml
Verifies the ability to continuously build.
> Add monthly build

- Directory.Packages.props
- src/LibraryManager/Json/LibraryStateToFileConverter.cs
- src/LibraryManager/Providers/BaseProvider.cs
- test/LibraryManager.IntegrationTest/InstallDialogTests.cs
- test/LibraryManager.IntegrationTest/LibmanCompletionTests.cs
Update select packages
Fix NRE from destination being null
Update expected version to '3.0'
Fix comment
Update test based on modern responses from unpkg
> Set of changes to get librarymanager 'fully passing'

- .context/TSAConfig.gdntsa
- azure-pipelines/official.yml
> Add TSA options

- Directory.Packages.props
- global.json
- src/LibraryManager/Providers/BaseProvider.cs
- src/LibraryManager/SemanticVersion.cs
Update versions to allow integration tests to run on 17.14
> Update versions to allow integration tests to run on 17.14

- src/LibraryManager.Vsix/source.extension.vsixmanifest
Expand the range in the vsix manifest
> Expand the range in the vsix manifest
